### PR TITLE
Edit SDL

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/310740/
https://steamdb.info/app/252630/

### Brief explanation of the change
The Mac OS X depots for both of these games have folders named "SDL2.framework". Inside there are files named "SDL2" with no file extension.

### CODE REVIEW

**Comment by Lifeismana** [comment]
look for sdl2.framework or else keeping .dll is useless

**Comment by MichaelHinrichs** [comment]
All i did was rename the branch, and that CLOSED this pull request? This is stupid!

**Comment by Lifeismana** [comment]
Ah, probably because pr are linked to the branch

**Comment by MichaelHinrichs** [comment]
But it's still the same branch.

**Pull request closed without merging**
