### PR TITLE
add Blitz3D

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

https://steamdb.info/app/1304510/
https://steamdb.info/app/1782380/

### Brief explanation of the change

added Blitz3D detection by ``.b3d`` files

### CODE REVIEW

**Comment by diedyesterdaywashere** [comment]
image
uh?

**Comment by diedyesterdaywashere** [comment]
idk i haven't commited to this repo in like 6 months, i forgot how any of this works

**Comment by diedyesterdaywashere** [comment]
@Lifeismana could you help me out pls?

**Comment by MichaelHinrichs** [comment]
Capitalize the "d" in the file name "descriptions/Engine.Blitz3d.md".

**Comment by diedyesterdaywashere** [comment]
> Capitalize the "3d" in the file name "descriptions/Engine.Blitz3d.md".

oh yea, completely forgot about that...

**Comment by Lifeismana** [comment]
Can you check if there's any obvious false positive ?
* [19201 - Tank Universal File](https://steamdb.info/depot/19201/)
* [19202 - Tank Universal russian](https://steamdb.info/depot/19202/)
* [25931 - east_india_company_content](https://steamdb.info/depot/25931/)
* [39371 - Xango Tango content](https://steamdb.info/depot/39371/)
* [41661 - tommy tronic content](https://steamdb.info/depot/41661/)
* [41662 - Tommy Tronic French](https://steamdb.info/depot/41662/)
* [41663 - Tommy Tronic Spanish](https://steamdb.info/depot/41663/)
* [41664 - Tommy Tronic German](https://steamdb.info/depot/41664/)
* [41671 - tommy tronic demo content](https://steamdb.info/depot/41671/)
* [42821 - east_india_trafalgar_content](https://steamdb.info/depot/42821/)
* [42822 - East India Company Battle of Trafalgar German](https://steamdb.info/depot/42822/)
* [42823 - East India Company Battle of Trafalgar French](https://steamdb.info/depot/42823/)
* [49301 - Commander Conquest of the Americas Content](https://steamdb.info/depot/49301/)
* [49310 - Commander COTA DLC - Colonial Navy](https://steamdb.info/depot/49310/)
* [49311 - Commander COTA DLC - Pirate Treasure Chest](https://steamdb.info/depot/49311/)
* [49321 - Woody Two Legs GM](https://steamdb.info/depot/49321/)
* [202411 - Scoregasm Depot](https://steamdb.info/depot/202411/)
* [202413 - Scoregasm Mac Depot](https://steamdb.info/depot/202413/)
* [206651 - Scoregasm Demo Depot](https://steamdb.info/depot/206651/)
* [254001 - East India Company Gold Content](https://steamdb.info/depot/254001/)
* [254021 - Commander: Conquest of the Americas Gold Content](https://steamdb.info/depot/254021/)
* [267655 - Dépôt : Firefly (267655)](https://steamdb.info/depot/267655/)
* [285351 - Kingdom Elemental Content](https://steamdb.info/depot/285351/)
* [304691 - Star Sonata 2](https://steamdb.info/depot/304691/)
* [316951 - War Operations Content](https://steamdb.info/depot/316951/)
* [320321 - Darkstone Content](https://steamdb.info/depot/320321/)
* [327491 - RTS Creator Content](https://steamdb.info/depot/327491/)
* [335411 - RTS Creator Demo Content](https://steamdb.info/depot/335411/)
* [339861 - Ancients of Fasaria: Celestias Angelica Content](https://steamdb.info/depot/339861/)
* [366701 - Breakout Invaders Content](https://steamdb.info/depot/366701/)
* [368721 - Sirius Online Content](https://steamdb.info/depot/368721/)
* [370311 - Tompi Jones Content](https://steamdb.info/depot/370311/)
* [373671 - Arkhelom 3D Content](https://steamdb.info/depot/373671/)
* [401421 - Match 3 Revolution Content](https://steamdb.info/depot/401421/)
* [515800 - Fasaria World: Ancients of Moons MMORPG (515800) Depot](https://steamdb.info/depot/515800/)
* [523031 - Tank Universal 2 Content](https://steamdb.info/depot/523031/)
* [546821 - Pony World 2 Content](https://steamdb.info/depot/546821/)
* [640121 - Youropa Content](https://steamdb.info/depot/640121/)
* [765371 - RTS Commander: Smash The Rebels Content](https://steamdb.info/depot/765371/)
* [798711 - Voltage Content](https://steamdb.info/depot/798711/)
* [806221 - Absolute Blue Content](https://steamdb.info/depot/806221/)
* [814521 - RTS Commander: Smash the Rebels Demo Content](https://steamdb.info/depot/814521/)
* [839041 - Fasaria Classics [LEGACY] Content](https://steamdb.info/depot/839041/)
* [952141 - Surrogate Content](https://steamdb.info/depot/952141/)
* [1304401 - The End of Dyeus (Windows)](https://steamdb.info/depot/1304401/)
* [1304402 - The End of Dyeus (Linux)](https://steamdb.info/depot/1304402/)
* [1304511 - SCP: Nine-Tailed Fox Content](https://steamdb.info/depot/1304511/)
* [1612991 - The End of Dyeus Playtest (Windows)](https://steamdb.info/depot/1612991/)
* [1612992 - The End of Dyeus Playtest (Linux)](https://steamdb.info/depot/1612992/)
* [1641061 - Castles & Catapults Content](https://steamdb.info/depot/1641061/)
* [1782381 - SCP Containment Breach Multiplayer Content](https://steamdb.info/depot/1782381/)
* [1801281 - SCP: CB Multiplayer Dedicated Server Content](https://steamdb.info/depot/1801281/)
* [2090232 - ](https://steamdb.info/depot/2090232/)

**Comment by diedyesterdaywashere** [comment]
hmm... that's a hard one, most games are not popular so there's little to no info about engines used in these games..

**Pull request merged**
