### PR TITLE
Add Visual Novel Maker

### PR DESCRIPTION
**Pull request by andOlga**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1014580
https://steamdb.info/app/1118910
https://steamdb.info/app/1116660
https://steamdb.info/app/949670
...and basically everything listed on [this board](https://steamcommunity.com/app/495480/discussions/2/), and then some.

### Brief explanation of the change
This adds the Visual Novel Maker engine ([official website](https://visualnovelmaker.com/), [Steam store page](https://store.steampowered.com/app/495480/Visual_Novel_Maker/)), which is, as the name implies, an engine for creating visual novels. It's from the same company that made RPG Maker.

### CODE REVIEW

**Comment by xPaw** [comment]
Are there games that need .json.js detection, where .vndata is not enough?

**Comment by andOlga** [comment]
Yes. I suppose technically speaking the bizarre .json.js pattern is more accurate and all games match it, whereas `settings.vndata` is just *common*, but not universal. Shall I remove the `.vndata`?

**Comment by xPaw** [comment]
I don't quite like the .json.js detection because it's quite generic.

**Comment by andOlga** [comment]
I have found a less generic and universal file we can use. I think using a unique filename, combined with a bizarre `.json.js` extension (seriously, never saw that outside of this engine -- just `.json` or just `.js`, absolutely, but not a combination like that) is an improvement.

**Comment by xPaw** [comment]
`.json.js` is actually common for some JS bundlers where they put json inside of a JSON.parse because it's faster to parse.

**Comment by andOlga** [comment]
I see, didn't know that. Would you consider the path of `data/summaries.json.js` unique enough?
If not, we could latch onto `settings.vndata`, and eat the false negatives. I'm not entirely sure why this file is missing, it seems like a "this is included in most builds but is created by the engine at first start-up if it's not there" type of deal.
Unfortunately after digging through every file, I couldn't find anything more unqiue than these two.

**Pull request merged**
