### PR TITLE
Change names of technologies to look better

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

pls no

### Brief explanation of the change
Changed names of technologies to look better (rn i only touched rules i contributed, but if i get permission i'll change some other)

### CODE REVIEW

**Comment by Lifeismana** [comment]
C4 Engine's name is C4 Engine, not simply C4
Amazon Lumberyard, i don't mind
& for EAAntiCheat, i would prefer EA_AntiCheat (without the dash)

You don't have to limit yourself to the things you did but please, don't group every changes in one PR

**Comment by diedyesterdaywashere** [comment]
i'll just make changes you mentioned and then make diff pr for every change

**Comment by Lifeismana** [comment]
Don't make one pr per change but group them by category, for example

**Comment by diedyesterdaywashere** [comment]
oki, im just sending last commit and this issue can be closed i guess

**Pull request merged**
