### PR TITLE
Add GDevelop

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/761000/
https://steamdb.info/app/765480/
https://steamdb.info/app/2216980/

### Brief explanation of the change
Detect GDevelop by it's JS files.

### CODE REVIEW

**Comment by MichaelHinrichs** [comment]
Fucking shithell!

**Comment by Bouh** [comment]
This rules cannot works because all these files are packaged in a file. 
There is no folder or file with a GDevelop marker.

Issue related to https://github.com/SteamDatabase/FileDetectionRuleSets/pull/54

The most simple thing is for the engine, to create a text file with a license, like `license.GDevelop.txt`.

**Comment by Bouh** [comment]
## Solution 

A file will be added to the engine, this file could be used.
https://github.com/4ian/GDevelop/pull/6423

The rule can be:
```JS
GDevelop = (?:^|/)LICENSE\.gdevelop\.txt$
```

**Comment by Lifeismana** [comment]
merged in https://github.com/SteamDatabase/FileDetectionRuleSets/commit/54b9666941f1d55a17088cbbbebd5965487c77a9

**Comment by Lifeismana** [comment]
@Bouh feel free to make a pr (again) once you end up merging your pr in your repo
looking for `GDCpp.dll` and files starting with `gdjs-evtsext__` should be enough for now but with that licence file it should future proof the regex

**Pull request closed without merging**
