### PR TITLE
Construct

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1715840/
https://steamdb.info/app/1567580/
https://steamdb.info/app/382260/
https://steamdb.info/app/1310790/
https://steamdb.info/app/787220/
https://steamdb.info/app/744800/
https://steamdb.info/app/738720/
https://steamdb.info/app/971210/
https://steamdb.info/app/2295650/
https://steamdb.info/app/429160/
https://steamdb.info/app/904700/
https://steamdb.info/app/1094580/
https://steamdb.info/app/2077100/
https://steamdb.info/app/2058060/
https://steamdb.info/app/918740/
https://steamdb.info/app/1740730/
https://steamdb.info/app/2287080/
https://steamdb.info/app/2209020/
https://steamdb.info/app/1577970/
https://steamdb.info/app/1444670/
https://steamdb.info/app/1590360/
https://steamdb.info/app/868710/
https://steamdb.info/app/1614040/
https://steamdb.info/app/1825650/
https://steamdb.info/app/1973040/
https://steamdb.info/app/719110/
https://steamdb.info/app/1522660/
https://steamdb.info/app/1359300/
https://steamdb.info/app/1254720/
https://steamdb.info/app/1598560/
https://steamdb.info/app/1649280/
https://steamdb.info/app/2233300/
https://steamdb.info/app/395520/
https://steamdb.info/app/1503540/
https://steamdb.info/app/897120/
https://steamdb.info/app/1347140/
https://steamdb.info/app/1726020/
https://steamdb.info/app/1596380/
https://steamdb.info/app/1452860/
https://steamdb.info/app/402980/
https://steamdb.info/app/514390/
https://steamdb.info/app/1227750/
https://steamdb.info/app/697970/
https://steamdb.info/app/1582900/
https://steamdb.info/app/1555380/
https://steamdb.info/app/385980/
https://steamdb.info/app/365270/
https://steamdb.info/app/753440/
https://steamdb.info/app/690060/
https://steamdb.info/app/598170/
https://steamdb.info/app/1012490/
https://steamdb.info/app/1034170/
https://steamdb.info/app/1646050/
https://steamdb.info/app/1047430/
https://steamdb.info/app/2497430/

### Brief explanation of the change
Detect package.nw, a zipped archive that many Construct games use to store assets. It always contains either c2runtime.js or c3runtime.js.

### CODE REVIEW

**Comment by xPaw** [comment]
package.nw is documented here: https://github.com/SteamDatabase/FileDetectionRuleSets/blob/21829b34e8c3ff38826d632413dedcee4294120c/KNOWN_UNDETECTIONS.md?plain=1#L11

**Comment by MichaelHinrichs** [comment]
Steam DB detects 20 Construct games in my library. I have 87 in my Construct collection. That's 67 games that Steam DB missed. 67 games that I checked myself. Each one had a package.nw file. I checked each and every one. Out of 67 games, not one failed to contain Construct's libraries. I still have yet to find one that does. If such a game with such a file exists, then show it to me!

**Comment by Lifeismana** [comment]
you might need to reread the quote that xPaw sent, especially this part:
> which hides this information from us and makes it indistinguishable from a generic Node.JS game

**Comment by MichaelHinrichs** [comment]
And yet a have no proof of such a "generic node js game". If a package.nw file without construct exists, I need to see it.

**Pull request closed without merging**
