### PR TITLE
Improve GoldSource detection

### PR DESCRIPTION
**Pull request by Velaron**
### SteamDB app page links to a few games using this
https://store.steampowered.com/app/261980/HalfLife_Before/
https://store.steampowered.com/app/1283930/HalfLife_Restored/

### Brief explanation of the change
Checking for hltv.exe is not a reliable method, while liblist.gam is mandatory for GoldSrc mods.

### CODE REVIEW

**Review by a1batross — APPROVED** [review]
+1 that

liblist.gam also used internally by Steam to detect non-Steam Half-Life mods.

**Comment by Lifeismana** [comment]
Here's the list of app that this would match, GMod & Portal 2 are GoldSource games ? that looks like a false positive to me

* [1 - Base Goldsrc Shared Content](https://steamdb.info/depot/1/)
* [11 - Counter-Strike Base Content](https://steamdb.info/depot/11/)
* [21 - Team Fortress Classic Base Content](https://steamdb.info/depot/21/)
* [31 - Day of Defeat Base Content](https://steamdb.info/depot/31/)
* [41 - Deathmatch Classic Base Content](https://steamdb.info/depot/41/)
* [51 - Opposing Force Base Content](https://steamdb.info/depot/51/)
* [61 - Ricochet Base Content](https://steamdb.info/depot/61/)
* [81 - Condition Zero Base Content](https://steamdb.info/depot/81/)
* [101 - Condition Zero Deleted Scenes Base Content](https://steamdb.info/depot/101/)
* [130 - Half-Life: Blue Shift](https://steamdb.info/depot/130/)
* [221 - Half-Life 2 Base](https://steamdb.info/depot/221/)
* [233 - Half-Life 2 Demo base](https://steamdb.info/depot/233/)
* [241 - CS:S Client server shared](https://steamdb.info/depot/241/)
* [301 - DoD:S Client server shared](https://steamdb.info/depot/301/)
* [321 - HL2:DM Client server shared](https://steamdb.info/depot/321/)
* [361 - HL1:MP Client server shared](https://steamdb.info/depot/361/)
* [401 - Portal](https://steamdb.info/depot/401/)
* [409 - Portal Demo Base](https://steamdb.info/depot/409/)
* [521 - TF2 Beta Client server shared](https://steamdb.info/depot/521/)
* [621 - portal 2 common](https://steamdb.info/depot/621/)
* [631 - alien swarm content](https://steamdb.info/depot/631/)
* [731 - Counter-Strike Global Offensive Beta Common](https://steamdb.info/depot/731/)
* [1841 - ValveTestApp1840 content](https://steamdb.info/depot/1841/)
* [2131 - MM_MP_Engine](https://steamdb.info/depot/2131/)
* [2144 - MM_MP_Server](https://steamdb.info/depot/2144/)
* [2402 - The Ship Common](https://steamdb.info/depot/2402/)
* [4001 - GMOD Content](https://steamdb.info/depot/4001/)
* [4021 - Garry's Mod Dedicated Server Content](https://steamdb.info/depot/4021/)
* [10224 - Postal III Content](https://steamdb.info/depot/10224/)
* [17511 - age of chivalry content](https://steamdb.info/depot/17511/)
* [17551 - Eternal-Silence content](https://steamdb.info/depot/17551/)
* [17571 - pvkii content](https://steamdb.info/depot/17571/)
* [17581 - Dystopia Content](https://steamdb.info/depot/17581/)
* [17591 - Dystopia Beta Content](https://steamdb.info/depot/17591/)
* [17711 - Nuclear Dawn Content](https://steamdb.info/depot/17711/)
* [17744 - Source 2013 Multiplayer Windows](https://steamdb.info/depot/17744/)
* [17745 - Source 2013 Multiplayer Linux](https://steamdb.info/depot/17745/)
* [17771 - SDK Files](https://steamdb.info/depot/17771/)
* [22202 - ZenoClashContent](https://steamdb.info/depot/22202/)
* [22222 - ZenoClashContentDemo](https://steamdb.info/depot/22222/)
* [70001 - dinodday](https://steamdb.info/depot/70001/)
* [91701 - E.Y.E content](https://steamdb.info/depot/91701/)
* [91702 - EYE_DS](https://steamdb.info/depot/91702/)
* [203811 - Dear Esther Depot](https://steamdb.info/depot/203811/)
* [203812 - Dear Esther Mac Depot](https://steamdb.info/depot/203812/)
* [213631 - Portal 2 Edu Common](https://steamdb.info/depot/213631/)
* [214821 - EYE Cybermancy Demo](https://steamdb.info/depot/214821/)
* [223711 - Cry of Fear Content](https://steamdb.info/depot/223711/)
* [224261 - No More Room in Hell Content](https://steamdb.info/depot/224261/)
* [224265 - No More Room in Hell SDK2013 Windows Content](https://steamdb.info/depot/224265/)
* [224266 - No More Room in Hell SDK2013 Linux Content](https://steamdb.info/depot/224266/)
* [224267 - No More Room in Hell SDK2013 Mac Content](https://steamdb.info/depot/224267/)
* [225841 - Base content](https://steamdb.info/depot/225841/)
* [229830 - TF2 Beta Dedicated server assets](https://steamdb.info/depot/229830/)
* [232290 - DoD:S Dedicated server assets](https://steamdb.info/depot/232290/)
* [232330 - CS:S Dedicated server assets](https://steamdb.info/depot/232330/)
* [232370 - HL2:DM Dedicated server assets](https://steamdb.info/depot/232370/)
* [243731 - Source SDK Base 2013 Singleplayer Content](https://steamdb.info/depot/243731/)
* [243751 - Source SDK Base 2013 Multiplayer Content](https://steamdb.info/depot/243751/)
* [244311 - Source SDK Base 2013 Dedicated server assets](https://steamdb.info/depot/244311/)
* [244631 - NEOTOKYO Content](https://steamdb.info/depot/244631/)
* [247121 - Portal 2 Sixense Perceptual Pack Content](https://steamdb.info/depot/247121/)
* [251111 - INFRA Base Content](https://steamdb.info/depot/251111/)
* [253531 - Base Content](https://steamdb.info/depot/253531/)
* [255470 - HL1:MP Dedicated server assets](https://steamdb.info/depot/255470/)
* [261981 - Half-Life: Before 2 Depot](https://steamdb.info/depot/261981/)
* [264241 - CONSORTIUM Release (Base)](https://steamdb.info/depot/264241/)
* [265631 - os neutral](https://steamdb.info/depot/265631/)
* [266431 - Anarchy Arcade Content](https://steamdb.info/depot/266431/)
* [270371 - Lambda Wars Content](https://steamdb.info/depot/270371/)
* [282841 - Half Life 2: Enhancement Mod Common](https://steamdb.info/depot/282841/)
* [285561 - HL2CTF 2.5 Content](https://steamdb.info/depot/285561/)
* [286085 - TWTM P2 content](https://steamdb.info/depot/286085/)
* [290931 - Half-Life 2: Update Content](https://steamdb.info/depot/290931/)
* [290940 - Half-Life 2: Update OSX Depot](https://steamdb.info/depot/290940/)
* [290941 - Half-Life 2: Update Windows Depot](https://steamdb.info/depot/290941/)
* [290942 - Half-Life 2: Update Linux Depot](https://steamdb.info/depot/290942/)
* [295231 - Fistfull of Frags Dedicated Server Content](https://steamdb.info/depot/295231/)
* [302811 - Windows](https://steamdb.info/depot/302811/)
* [303211 - The Beginner's Guide Content & win32](https://steamdb.info/depot/303211/)
* [313241 - Wilson Chronicles Content](https://steamdb.info/depot/313241/)
* [313601 - NEOTOKYO Dedicated Server Content](https://steamdb.info/depot/313601/)
* [314281 - Shared](https://steamdb.info/depot/314281/)
* [317343 - prototype](https://steamdb.info/depot/317343/)
* [317361 - Source SDK 2013 Multiplayer Windows](https://steamdb.info/depot/317361/)
* [317362 - Source SDK 2013 Multiplayer Linux](https://steamdb.info/depot/317362/)
* [317363 - Source SDK 2013 Multiplayer OSX](https://steamdb.info/depot/317363/)
* [317364 - Double Action Mod Directory](https://steamdb.info/depot/317364/)
* [317401 - Portal Stories: Mel Content](https://steamdb.info/depot/317401/)
* [317405 - Portal Stories: Mel p2content](https://steamdb.info/depot/317405/)
* [317671 - No More Room in Hell Dedicated Server Content Windows](https://steamdb.info/depot/317671/)
* [317672 - No More Room in Hell Dedicated Server Content Linux](https://steamdb.info/depot/317672/)
* [317673 - No More Room in Hell Dedicated Server Shared Content](https://steamdb.info/depot/317673/)
* [317792 - Portal Base Windows](https://steamdb.info/depot/317792/)
* [317793 - Portal Base Mac](https://steamdb.info/depot/317793/)
* [317794 - Portal Base Linux](https://steamdb.info/depot/317794/)
* [317801 - Source SDK 2013 Dedicated Server Windows](https://steamdb.info/depot/317801/)
* [317802 - Source SDK 2013 Dedicated Server Linux](https://steamdb.info/depot/317802/)
* [320995 - Portal 2 Content (320995) Depot](https://steamdb.info/depot/320995/)
* [329711 - Fortress Forever Dedicated Server Content](https://steamdb.info/depot/329711/)
* [331030 - Pirates, Vikings, and Knights II Dedicated Server Content](https://steamdb.info/depot/331030/)
* [334371 - From Earth Content](https://steamdb.info/depot/334371/)
* [346331 - Shared Content](https://steamdb.info/depot/346331/)
* [349484 - Modular Combat 2007 Release](https://steamdb.info/depot/349484/)
* [353221 - Хранилище Fast Detect](https://steamdb.info/depot/353221/)
* [354901 - Headcrab Frenzy Common Content](https://steamdb.info/depot/354901/)
* [355181 - Codename CURE Content](https://steamdb.info/depot/355181/)
* [365301 - Transmissions: Element 120 Content](https://steamdb.info/depot/365301/)
* [383411 - Codename CURE Dedicated Server Content](https://steamdb.info/depot/383411/)
* [397682 - FIREFIGHT RELOADED Game Assets](https://steamdb.info/depot/397682/)
* [399125 - Prospekt Depot - 10-01-2016](https://steamdb.info/depot/399125/)
* [408091 - Missing Information Content](https://steamdb.info/depot/408091/)
* [433971 - Destroyed Aperture Content](https://steamdb.info/depot/433971/)
* [460044 - Source 2013 Dedicated Server Windows](https://steamdb.info/depot/460044/)
* [460045 - Source 2013 Dedicated Server Linux](https://steamdb.info/depot/460045/)
* [475371 - Shared Content](https://steamdb.info/depot/475371/)
* [494771 - FIREFIGHT RELOADED Dedicated Server Content](https://steamdb.info/depot/494771/)
* [563561 - Alien Swarm: Reactive Drop Content](https://steamdb.info/depot/563561/)
* [587651 - Half-Life 2: DownFall Content](https://steamdb.info/depot/587651/)
* [600381 - Classic Offensive Client Content](https://steamdb.info/depot/600381/)
* [601361 - Portal: Revolution Game](https://steamdb.info/depot/601361/)
* [626681 - Kreedz Climbing Base Content](https://steamdb.info/depot/626681/)
* [628411 - Arctic Adventure: Episodes Content](https://steamdb.info/depot/628411/)
* [629511 - Arctic Adventure: Episodes Demo Content](https://steamdb.info/depot/629511/)
* [632731 - Base Defense Content](https://steamdb.info/depot/632731/)
* [638101 - Kreedz Climbing Dedicated Server Base Content](https://steamdb.info/depot/638101/)
* [638361 - Parasomnia - Content](https://steamdb.info/depot/638361/)
* [638801 - The Trap 2: Mindlock (beta) Depot](https://steamdb.info/depot/638801/)
* [638804 - The Trap 2: Mindlock (beta)](https://steamdb.info/depot/638804/)
* [644321 - Halfquake Trilogy Content](https://steamdb.info/depot/644321/)
* [656801 - Infestus Content](https://steamdb.info/depot/656801/)
* [658921 - Half-Life 2: VR](https://steamdb.info/depot/658921/)
* [661351 - Infestus Dedicated Server Content](https://steamdb.info/depot/661351/)
* [669271 - Momentum Mod Content](https://steamdb.info/depot/669271/)
* [679991 - Half-Life: Caged Content](https://steamdb.info/depot/679991/)
* [684891 - Source VR Content](https://steamdb.info/depot/684891/)
* [714071 - Entropy : Zero Content](https://steamdb.info/depot/714071/)
* [723391 - Hunt Down The Freeman](https://steamdb.info/depot/723391/)
* [747251 - Half-Life 2: Year Long Alarm Content](https://steamdb.info/depot/747251/)
* [812371 - Boreal Alyph Content](https://steamdb.info/depot/812371/)
* [812441 - Half-Life: Absolute Zero Content](https://steamdb.info/depot/812441/)
* [817301 - Base Defense Dedicated Server Content](https://steamdb.info/depot/817301/)
* [850871 - Hard-Life Content](https://steamdb.info/depot/850871/)
* [944230 - Team Fortress 2008 - Dedicated Server Depot](https://steamdb.info/depot/944230/)
* [955081 - Team Fortress 2008 - Dedicated Server Content](https://steamdb.info/depot/955081/)
* [977052 - Windows Base](https://steamdb.info/depot/977052/)
* [977053 - Linux Base](https://steamdb.info/depot/977053/)
* [985051 - Action: Source Windows Dedicated Server Base](https://steamdb.info/depot/985051/)
* [985052 - Action: Source Linux Dedicated Server Base](https://steamdb.info/depot/985052/)
* [1007091 - The Burton Equation Content](https://steamdb.info/depot/1007091/)
* [1054601 - Resistance Element Content](https://steamdb.info/depot/1054601/)
* [1057701 - Battle Grounds III Content](https://steamdb.info/depot/1057701/)
* [1066611 - Digital Paintball Redux Content](https://steamdb.info/depot/1066611/)
* [1117391 - Snowdrop Escape Content](https://steamdb.info/depot/1117391/)
* [1154131 - Base](https://steamdb.info/depot/1154131/)
* [1196274 - ](https://steamdb.info/depot/1196274/)
* [1196641 - Team Fortress Classic: Source Content](https://steamdb.info/depot/1196641/)
* [1197421 - TFC:S Dedicated Server Content](https://steamdb.info/depot/1197421/)
* [1224601 - G String Content](https://steamdb.info/depot/1224601/)
* [1255981 - Portal Reloaded Shared Content](https://steamdb.info/depot/1255981/)
* [1274451 - Bear Party: Adventure Content](https://steamdb.info/depot/1274451/)
* [1274453 - Bear Party: Adventure Linux](https://steamdb.info/depot/1274453/)
* [1283939 - Half-Life: Restored Depot](https://steamdb.info/depot/1283939/)
* [1341061 - Half-Life 2: Genry's Great Escape From City 13 Content](https://steamdb.info/depot/1341061/)
* [1389951 - Amalgam Content](https://steamdb.info/depot/1389951/)
* [1435321 - Deathmatch Classic: Refragged](https://steamdb.info/depot/1435321/)
* [1440552 - Deathmatch Classic: Refragged Dedicated server assets](https://steamdb.info/depot/1440552/)
* [1583721 - ](https://steamdb.info/depot/1583721/)
* [1786951 - ](https://steamdb.info/depot/1786951/)
* [1828211 - Requiem Of Science Content](https://steamdb.info/depot/1828211/)
* [1828212 - Requiem Of Science RUS](https://steamdb.info/depot/1828212/)
* [1828213 - ](https://steamdb.info/depot/1828213/)
* [1865401 - Things Between Content](https://steamdb.info/depot/1865401/)
* [1865461 - Things Between Playtest Content](https://steamdb.info/depot/1865461/)
* [1875451 - Treason Playtest Depot](https://steamdb.info/depot/1875451/)
* [1875501 - Treason Dedicated Server Content](https://steamdb.info/depot/1875501/)
* [1889471 - Half-Life Decay: Solo Mission Demo Content](https://steamdb.info/depot/1889471/)
* [1908721 - ](https://steamdb.info/depot/1908721/)

**Comment by diedyesterdaywashere** [comment]
@Lifeismana would you pls merge this one?

**Comment by Lifeismana** [comment]
nah, negative lookback is not something that we want to have in the repo, so this must be done in an other way that i'm looking into

**Comment by diedyesterdaywashere** [comment]
just look for file only in root? or idk how it works

**Comment by Velaron** [comment]
> just look for file only in root? or idk how it works

The problem is it's not in the root, it's located in a subfolder like "valve"

**Comment by diedyesterdaywashere** [comment]
only in valve? or names can differ? even if they can its possible to search for them all if we have a list of them

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.GoldSource**

These apps no longer match: **(1)** [5](https://steamdb.info/app/5/depots/)

These apps now match: **(29)** [10](https://steamdb.info/app/10/depots/) [20](https://steamdb.info/app/20/depots/) [30](https://steamdb.info/app/30/depots/) [40](https://steamdb.info/app/40/depots/) [50](https://steamdb.info/app/50/depots/) [60](https://steamdb.info/app/60/depots/) [70](https://steamdb.info/app/70/depots/) [80](https://steamdb.info/app/80/depots/) [90](https://steamdb.info/app/90/depots/) [100](https://steamdb.info/app/100/depots/) [130](https://steamdb.info/app/130/depots/) [223710](https://steamdb.info/app/223710/depots/) [225840](https://steamdb.info/app/225840/depots/) [261980](https://steamdb.info/app/261980/depots/) [276060](https://steamdb.info/app/276060/depots/) [354900](https://steamdb.info/app/354900/depots/) [632730](https://steamdb.info/app/632730/depots/) [638360](https://steamdb.info/app/638360/depots/) [644320](https://steamdb.info/app/644320/depots/) [679990](https://steamdb.info/app/679990/depots/) [812440](https://steamdb.info/app/812440/depots/) [817300](https://steamdb.info/app/817300/depots/) [850870](https://steamdb.info/app/850870/depots/) [1066610](https://steamdb.info/app/1066610/depots/) [1283930](https://steamdb.info/app/1283930/depots/) [1761270](https://steamdb.info/app/1761270/depots/) [1889470](https://steamdb.info/app/1889470/depots/) [1908720](https://steamdb.info/app/1908720/depots/) [2842160](https://steamdb.info/app/2842160/depots/)

Please confirm that all these changed apps are correct.

**Comment by Velaron** [comment]
All the matches are correct, not sure about the no longer matching one. Technically it is GoldSrc, but it's not really a game, just the engine executables so it doesn't match with this method.

**Comment by xPaw** [comment]
Detecting liblist is a good idea, but the comment about negative lookback still applies unfortunately.

**Pull request closed without merging**
