### PR TITLE
Add support for detecting Clausewitz engine

### PR DESCRIPTION
**Pull request by paavohuhtala**
### SteamDB app page links to a few games using this

https://steamdb.info/app/203770/
https://steamdb.info/app/1158310/
https://steamdb.info/app/281990/
https://steamdb.info/app/25800/
https://steamdb.info/app/236850/
https://steamdb.info/app/859580/
https://steamdb.info/app/25890/
https://steamdb.info/app/394360/

### Brief explanation of the change

Adds support for Clausewitz engine, the in-house game engine of [Paradox Development Studio](https://en.wikipedia.org/wiki/Paradox_Development_Studio).

The file names used are kind of generic, so false positives are possible. To mitigate that I've chosen to essentially hardcode the paths instead of using the common `(?:^|/)` prefix, and I've verified that this works with all released Clausewitz games I'm aware of. There are more specific detection methods that could be used with individual games, but nothing as generic as these two regexes.

### CODE REVIEW

**Comment by xPaw** [comment]
Seems like `common/defines.lua` is not always in root.

I searched for `common/defines`, and here are all the depots that matched:
* [22151 - europa universalis iii demo content](https://steamdb.info/depot/22151/)
* [22161 - europa universalis rome demo content](https://steamdb.info/depot/22161/)
* [23421 - Europa Universalis Rome content](https://steamdb.info/depot/23421/)
* [25801 - europa universalis iii content](https://steamdb.info/depot/25801/)
* [25806 - Europa Universalis III: Heir to the Throne](https://steamdb.info/depot/25806/)
* [25807 - europa universalis III mac content](https://steamdb.info/depot/25807/)
* [25808 - Europa Universalis III - Divine Wind](https://steamdb.info/depot/25808/)
* [25891 - hearts_of_iron_3_content](https://steamdb.info/depot/25891/)
* [25961 - hearts of iron 3 mac content](https://steamdb.info/depot/25961/)
* [42900 - Semper Fi Expansion](https://steamdb.info/depot/42900/)
* [42902 - Hearts of Iron III Semper Fi: Dies Irae Gotterdammerung](https://steamdb.info/depot/42902/)
* [42903 - Hearts of Iron III: For the Motherland](https://steamdb.info/depot/42903/)
* [42961 - victoria 2 content](https://steamdb.info/depot/42961/)
* [42968 - Victoria II - A House Divided](https://steamdb.info/depot/42968/)
* [61011 - A10_depots](https://steamdb.info/depot/61011/)
* [73081 - CKII Beta Main](https://steamdb.info/depot/73081/)
* [73211 - Sengoku Main](https://steamdb.info/depot/73211/)
* [203771 - CKIIMain](https://steamdb.info/depot/203771/)
* [206311 - CKII Demo Depot](https://steamdb.info/depot/206311/)
* [214986 - Hearts of Iron III: Their Finest Hour](https://steamdb.info/depot/214986/)
* [215001 - Victoria II - Heart of Darkness](https://steamdb.info/depot/215001/)
* [227761 - savecancel](https://steamdb.info/depot/227761/)
* [233031 - March of the Eagles Demo Content](https://steamdb.info/depot/233031/)
* [236851 - Europa Universalis IV Content](https://steamdb.info/depot/236851/)
* [247891 - Europa Universalis IV Demo Content](https://steamdb.info/depot/247891/)
* [281991 - Main](https://steamdb.info/depot/281991/)
* [393781 - Main](https://steamdb.info/depot/393781/)
* [394361 - Hearts of Iron IV Content](https://steamdb.info/depot/394361/)
* [859581 - Imperator: Rome Content](https://steamdb.info/depot/859581/)
* [859582 - Imperator: Rome Windows](https://steamdb.info/depot/859582/)
* [859583 - Imperator: Rome OSX](https://steamdb.info/depot/859583/)
* [859584 - Imperator: Rome Linux](https://steamdb.info/depot/859584/)
* [1158311 - CK3 Game Content](https://steamdb.info/depot/1158311/)
* [1158312 - CK3 Windows Binaries](https://steamdb.info/depot/1158312/)
* [1158313 - CK3 macOS Binaries](https://steamdb.info/depot/1158313/)
* [1158314 - CK3 Linux Binaries](https://steamdb.info/depot/1158314/)
Seems like you don't need to root it to `^`.

**Comment by paavohuhtala** [comment]
@xPaw  Is it possible to find out in which depot it's not under root? I clicked through most of your list and everything looks good, except for [61011 - A10_depots](https://steamdb.info/depot/61011/) which is a completely unrelated game and would be a false positive without the root requirement.

**Comment by paavohuhtala** [comment]
Ah, looks like Hearts of Iron III DLC's have a single folder before `common`.

**Comment by xPaw** [comment]
> except for 61011 - A10_depots which is a completely unrelated game 

It has `Bazar/shaders/model/common/defines.hlsl` which wouldn't match based on the extension.

**Comment by paavohuhtala** [comment]
Good point. I've amended the commit to remove the root requirement from the first rule, and tweaked the tests.

**Pull request merged**
