### PR TITLE
Add Creatures Engine

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1659050/
https://steamdb.info/app/1818340/
https://steamdb.info/app/1823900/

### Brief explanation of the change
Detect Creatures Engine

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.CreaturesEngine**

These apps now match: **(9)** [7220](https://steamdb.info/app/7220/depots/) [294720](https://steamdb.info/app/294720/depots/) [338090](https://steamdb.info/app/338090/depots/) [358340](https://steamdb.info/app/358340/depots/) [364810](https://steamdb.info/app/364810/depots/) [1449400](https://steamdb.info/app/1449400/depots/) [1659050](https://steamdb.info/app/1659050/depots/) [1818340](https://steamdb.info/app/1818340/depots/) [1823900](https://steamdb.info/app/1823900/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
too many false positive / not enough apps

**Pull request closed without merging**
