### PR TITLE
rename multiple sdks

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

https://steamdb.info/tech/SDK/EpicOnlineServices/

### Brief explanation of the change

added spaces for the name to look better on the main /tech page

### CODE REVIEW

**Comment by Lifeismana** [comment]
No need to rename gme

**Comment by diedyesterdaywashere** [comment]
> No need to rename gme

aight, just thought i'd rename it to it's official name (according to Unreal Engine plugin store and their website)

**Comment by diedyesterdaywashere** [comment]
here ya go

**Comment by xPaw** [comment]
This will break existing link, which I don't want to do (at least for EOS)

**Pull request closed without merging**
