### PR TITLE
Wave Engine

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/362350/

### Brief explanation of the change
Find Wave Engine by it's DLLs.

### CODE REVIEW

**Comment by Lifeismana** [comment]
Was looking at this pr, but there's only one app, do you know if there's more that the regex isn't catching ?

**Comment by MichaelHinrichs** [comment]
How about now?

**Comment by Lifeismana** [comment]
don't use these kind of regex

doesn't change anything, i was already looking for `WaveEngine`

**Comment by MichaelHinrichs** [comment]
Ok. i guess that's the only one then.

**Comment by MichaelHinrichs** [comment]
One question though. how is `(?:^|/)WaveEngine\..+\.dll$` any different from ` (?:^|/)(?:lib)?sfml-`? They both match nearly anything with the engine name in it. You wrote the second one in an edit to one of my pull requests.

**Pull request closed without merging**
