### PR TITLE
update CryEngine

### PR DESCRIPTION
**Pull request by diedyesterdaywastaken**
### SteamDB app page links to a few games using this

- [Homefront: The Revolution](https://steamdb.info/app/223100/)
- [Kingdom Come: Deliverance](https://steamdb.info/app/379430/)
- [Prey](https://steamdb.info/app/480490/)

### Brief explanation of the change

these CryEngine 4 games are not detected because they don't seem to have the right dlls, while I don't know why stuff like that happened, they should probably still get flagged ngl

imageimageimage

### CODE REVIEW

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.СryEngine**

These apps now match: **(77)** [220980](https://steamdb.info/app/220980/depots/) [223100](https://steamdb.info/app/223100/depots/) [244930](https://steamdb.info/app/244930/depots/) [261450](https://steamdb.info/app/261450/depots/) [261760](https://steamdb.info/app/261760/depots/) [268670](https://steamdb.info/app/268670/depots/) [286860](https://steamdb.info/app/286860/depots/) [293280](https://steamdb.info/app/293280/depots/) [299740](https://steamdb.info/app/299740/depots/) [302200](https://steamdb.info/app/302200/depots/) [302510](https://steamdb.info/app/302510/depots/) [304220](https://steamdb.info/app/304220/depots/) [328950](https://steamdb.info/app/328950/depots/) [348450](https://steamdb.info/app/348450/depots/) [350800](https://steamdb.info/app/350800/depots/) [355760](https://steamdb.info/app/355760/depots/) [368070](https://steamdb.info/app/368070/depots/) [371670](https://steamdb.info/app/371670/depots/) [371810](https://steamdb.info/app/371810/depots/) [379430](https://steamdb.info/app/379430/depots/) [392340](https://steamdb.info/app/392340/depots/) [412940](https://steamdb.info/app/412940/depots/) [417880](https://steamdb.info/app/417880/depots/) [424370](https://steamdb.info/app/424370/depots/) [431360](https://steamdb.info/app/431360/depots/) [434710](https://steamdb.info/app/434710/depots/) [442080](https://steamdb.info/app/442080/depots/) [442180](https://steamdb.info/app/442180/depots/) [443110](https://steamdb.info/app/443110/depots/) [444410](https://steamdb.info/app/444410/depots/) [452640](https://steamdb.info/app/452640/depots/) [466240](https://steamdb.info/app/466240/depots/) [470890](https://steamdb.info/app/470890/depots/) [474770](https://steamdb.info/app/474770/depots/) [480490](https://steamdb.info/app/480490/depots/) [508460](https://steamdb.info/app/508460/depots/) [555400](https://steamdb.info/app/555400/depots/) [568930](https://steamdb.info/app/568930/depots/) [573130](https://steamdb.info/app/573130/depots/) [579800](https://steamdb.info/app/579800/depots/) [579820](https://steamdb.info/app/579820/depots/) [589220](https://steamdb.info/app/589220/depots/) [594520](https://steamdb.info/app/594520/depots/) [594650](https://steamdb.info/app/594650/depots/) [609380](https://steamdb.info/app/609380/depots/) [611230](https://steamdb.info/app/611230/depots/) [622540](https://steamdb.info/app/622540/depots/) [632890](https://steamdb.info/app/632890/depots/) [643820](https://steamdb.info/app/643820/depots/) [644160](https://steamdb.info/app/644160/depots/) [646880](https://steamdb.info/app/646880/depots/) [673240](https://steamdb.info/app/673240/depots/) [678700](https://steamdb.info/app/678700/depots/) [724900](https://steamdb.info/app/724900/depots/) [770720](https://steamdb.info/app/770720/depots/) [809500](https://steamdb.info/app/809500/depots/) [877340](https://steamdb.info/app/877340/depots/) [882460](https://steamdb.info/app/882460/depots/) [893910](https://steamdb.info/app/893910/depots/) [897880](https://steamdb.info/app/897880/depots/) [912290](https://steamdb.info/app/912290/depots/) [921940](https://steamdb.info/app/921940/depots/) [973580](https://steamdb.info/app/973580/depots/) [1098270](https://steamdb.info/app/1098270/depots/) [1099220](https://steamdb.info/app/1099220/depots/) [1161220](https://steamdb.info/app/1161220/depots/) [1201440](https://steamdb.info/app/1201440/depots/) [1254490](https://steamdb.info/app/1254490/depots/) [1265650](https://steamdb.info/app/1265650/depots/) [1282690](https://steamdb.info/app/1282690/depots/) [1338770](https://steamdb.info/app/1338770/depots/) [1404150](https://steamdb.info/app/1404150/depots/) [1432740](https://steamdb.info/app/1432740/depots/) [1659210](https://steamdb.info/app/1659210/depots/) [1711430](https://steamdb.info/app/1711430/depots/) [1908800](https://steamdb.info/app/1908800/depots/) [2206760](https://steamdb.info/app/2206760/depots/)

Please confirm that all these changed apps are correct.

**Comment by diedyesterdaywastaken** [comment]
most of the games here already have cryengine detected, but some did not, and they're all cryengine 3/4/5

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.CryEngine**

**142** apps still match.

These apps now match: **(6)** [223100](https://steamdb.info/app/223100/depots/) [261760](https://steamdb.info/app/261760/depots/) [379430](https://steamdb.info/app/379430/depots/) [480490](https://steamdb.info/app/480490/depots/) [579820](https://steamdb.info/app/579820/depots/) [609380](https://steamdb.info/app/609380/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
Kinda hate this, but i guess there's no way around it

**Pull request merged**
