### PR TITLE
Add Chromium Embedded Framework

### PR DESCRIPTION
**Pull request by Lifeismana**
### SteamDB app page links to a few games using this
[Garry's Mod](https://steamdb.info/app/4000/depots/)
[SteamVR](https://steamdb.info/app/250820/)

### Brief explanation of the change
Added Chromium Embedded Framework as an SDK (Should i put it in the container category ?)
I was unable to find to a MacOs game that had cef, even though garry's mod has a OSX version it doesn't seem to be using cef for it

Also throwed `GenerateTestStrings.php` 's update of Nvidia Nsight in there.

### CODE REVIEW

**Comment by xPaw** [comment]
Isn't it libcef.dll? chrome_elf.dll is not CEF itself.

**Comment by Lifeismana** [comment]
Indeed, mistake on my side, it's only libcef

**Comment by xPaw** [comment]
can you rebase please

**Comment by Lifeismana** [comment]
Done

**Pull request merged**
