### PR TITLE
Add NScripter

### PR DESCRIPTION
**Pull request by andOlga**
### SteamDB app page links to a few games using this
https://steamdb.info/app/264380
https://steamdb.info/app/406550
https://steamdb.info/app/639490
https://steamdb.info/app/1162560

### Brief explanation of the change
Yes, another VN engine from me 😅 This is an older Japanese one. The engine itself is no longer updated, but still sees some use, including on Steam.

### CODE REVIEW

**Comment by xPaw** [comment]
Is one of these files common for all games? It's best when a detection can use least amount of variations.

**Comment by andOlga** [comment]
Unfortunately not, none of these are common for *all* games. Allow me to explain what the files for games using this engine *can* be:
- `0.txt` (excluded to the possibility of false positives): a plain-text script, encoded with [SJIS](https://en.wikipedia.org/wiki/Shift_JIS).
- `0.utf`: a plain-text script encoded as UTF-8.
- `nscript.dat`, an encrypted form of `0.txt`.
- `pscript.dat`, an encrypted form of `0.utf`.

Now, with that in mind, any NScripter game will have *at least one of these 4 files* (and usually none of the other ones), but since one of them is fairly generic I decided to go for a few extra files that *may* exist (but there are games where they don't):
- `arc.nsa`, an "archive" format used by the engine (basically stuffs the entirety of the game's data into one file instead of keeping it in separate ones)
- `ons.cfg` or `pns.cfg`, which are engine configuration files, used to set some options such as resolutions etc. If both of these are missing it uses default settings.

**Comment by xPaw** [comment]
Most common base names:
* `0.utf` - 4 matches

Depots that matched:
* [264381 - narci windows](https://steamdb.info/depot/264381/)
* [264382 - narci linux](https://steamdb.info/depot/264382/)
* [406551 - Umineko Win Depot](https://steamdb.info/depot/406551/)
* [639491 - Umineko When They Cry Chiru Content](https://steamdb.info/depot/639491/)

---

Most common base names:
* `arc.nsa` - 28 matches

Depots that matched:
* [264381 - narci windows](https://steamdb.info/depot/264381/)
* [264382 - narci linux](https://steamdb.info/depot/264382/)
* [406551 - Umineko Win Depot](https://steamdb.info/depot/406551/)
* [444951 - Let's Eat! Seaside Cafe Content](https://steamdb.info/depot/444951/)
* [558011 - REVIVAL RESET Content](https://steamdb.info/depot/558011/)
* [558711 - REVIVAL RESET Demo Content](https://steamdb.info/depot/558711/)
* [639491 - Umineko When They Cry Chiru Content](https://steamdb.info/depot/639491/)
* [924541 - NEVERMORE Content](https://steamdb.info/depot/924541/)
* [1082871 - NEVERMORE VIII-XIII Content](https://steamdb.info/depot/1082871/)
* [1162561 - Ciconia When They Cry Content](https://steamdb.info/depot/1162561/)
* [1189201 - MB JP](https://steamdb.info/depot/1189201/)
* [1189202 - MB SC](https://steamdb.info/depot/1189202/)
* [1189203 - MC TC](https://steamdb.info/depot/1189203/)
* [1246021 - NOeSIS01_Chinese](https://steamdb.info/depot/1246021/)
* [1246022 - NOeSIS-JP](https://steamdb.info/depot/1246022/)
* [1423371 - NOeSIS-羽化 China](https://steamdb.info/depot/1423371/)
* [1423372 - NOeSIS-羽化 Linux](https://steamdb.info/depot/1423372/)
* [1423373 - NOeSIS-羽化 JP](https://steamdb.info/depot/1423373/)
* [1455431 - JP](https://steamdb.info/depot/1455431/)
* [1455432 - SC](https://steamdb.info/depot/1455432/)
* [1455433 - TC](https://steamdb.info/depot/1455433/)
* [1558631 - JP](https://steamdb.info/depot/1558631/)
* [1558632 - SC](https://steamdb.info/depot/1558632/)
* [1558633 - TC](https://steamdb.info/depot/1558633/)
* [1614321 - NOeSIS-羽化 Playtest Content](https://steamdb.info/depot/1614321/)
* [1625231 - NOeSIS Ⅱ-人生无常 Content](https://steamdb.info/depot/1625231/)
* [1675151 - 「３」 Content](https://steamdb.info/depot/1675151/)
* [1855001 - NOeSIS Ⅱ-人生无常 Playtest Content](https://steamdb.info/depot/1855001/)

---

ons.cfg - none found

---

Most common base names:
* `pns.cfg` - 3 matches

Depots that matched:
* [264381 - narci windows](https://steamdb.info/depot/264381/)
* [264382 - narci linux](https://steamdb.info/depot/264382/)
* [1162561 - Ciconia When They Cry Content](https://steamdb.info/depot/1162561/)

---

Most common base names:
* `pscript.dat` - 1 matches

Depots that matched:
* [1162561 - Ciconia When They Cry Content](https://steamdb.info/depot/1162561/)

---

Most common base names:
* `nscript.dat` - 59 matches

Depots that matched:
* [444951 - Let's Eat! Seaside Cafe Content](https://steamdb.info/depot/444951/)
* [494091 - Dungeon Girl Content](https://steamdb.info/depot/494091/)
* [558011 - REVIVAL RESET Content](https://steamdb.info/depot/558011/)
* [558711 - REVIVAL RESET Demo Content](https://steamdb.info/depot/558711/)
* [817661 - Soul Smith of the Kingdom](https://steamdb.info/depot/817661/)
* [817662 - Soul Smith of the Kingdom CN](https://steamdb.info/depot/817662/)
* [817663 - Soul Smith of the Kingdom JP](https://steamdb.info/depot/817663/)
* [817664 - Soul Smith of the Kingdom CHT](https://steamdb.info/depot/817664/)
* [867121 - Lilipalace Content](https://steamdb.info/depot/867121/)
* [867122 - Lilipalace 日本語](https://steamdb.info/depot/867122/)
* [867123 - Lilipalace 繁体中国版](https://steamdb.info/depot/867123/)
* [882671 - Nono's magic general shop EN](https://steamdb.info/depot/882671/)
* [882672 - Nono's magic general shop CHS](https://steamdb.info/depot/882672/)
* [882673 - Nono's magic general shop CHT](https://steamdb.info/depot/882673/)
* [882674 - Nono's magic general shop JP](https://steamdb.info/depot/882674/)
* [924541 - NEVERMORE Content](https://steamdb.info/depot/924541/)
* [1053161 - Witch Ring Meister EN](https://steamdb.info/depot/1053161/)
* [1053162 - Witch Ring Meister CHS](https://steamdb.info/depot/1053162/)
* [1053163 - Witch Ring Meister CHT](https://steamdb.info/depot/1053163/)
* [1053164 - Witch Ring Meister JP](https://steamdb.info/depot/1053164/)
* [1082871 - NEVERMORE VIII-XIII Content](https://steamdb.info/depot/1082871/)
* [1141101 - Lilitales Content](https://steamdb.info/depot/1141101/)
* [1141102 - Lilitales Chinese](https://steamdb.info/depot/1141102/)
* [1147951 - Shio JP](https://steamdb.info/depot/1147951/)
* [1147952 - Shio SC](https://steamdb.info/depot/1147952/)
* [1147953 - Shio TC](https://steamdb.info/depot/1147953/)
* [1152351 - Shio Demo JP](https://steamdb.info/depot/1152351/)
* [1152352 - Shio Demo SC](https://steamdb.info/depot/1152352/)
* [1152353 - Shio Demo TC](https://steamdb.info/depot/1152353/)
* [1168431 - Dairy Princess JP](https://steamdb.info/depot/1168431/)
* [1168432 - Dairy Princess SC](https://steamdb.info/depot/1168432/)
* [1168433 - Dairy Princess TC](https://steamdb.info/depot/1168433/)
* [1189201 - MB JP](https://steamdb.info/depot/1189201/)
* [1189202 - MB SC](https://steamdb.info/depot/1189202/)
* [1189203 - MC TC](https://steamdb.info/depot/1189203/)
* [1246021 - NOeSIS01_Chinese](https://steamdb.info/depot/1246021/)
* [1246022 - NOeSIS-JP](https://steamdb.info/depot/1246022/)
* [1373181 - JP](https://steamdb.info/depot/1373181/)
* [1373182 - SC](https://steamdb.info/depot/1373182/)
* [1373183 - TC](https://steamdb.info/depot/1373183/)
* [1423371 - NOeSIS-羽化 China](https://steamdb.info/depot/1423371/)
* [1423372 - NOeSIS-羽化 Linux](https://steamdb.info/depot/1423372/)
* [1423373 - NOeSIS-羽化 JP](https://steamdb.info/depot/1423373/)
* [1455431 - JP](https://steamdb.info/depot/1455431/)
* [1455432 - SC](https://steamdb.info/depot/1455432/)
* [1455433 - TC](https://steamdb.info/depot/1455433/)
* [1558631 - JP](https://steamdb.info/depot/1558631/)
* [1558632 - SC](https://steamdb.info/depot/1558632/)
* [1558633 - TC](https://steamdb.info/depot/1558633/)
* [1614321 - NOeSIS-羽化 Playtest Content](https://steamdb.info/depot/1614321/)
* [1625231 - NOeSIS Ⅱ-人生无常 Content](https://steamdb.info/depot/1625231/)
* [1675151 - 「３」 Content](https://steamdb.info/depot/1675151/)
* [1760691 - JP](https://steamdb.info/depot/1760691/)
* [1760692 - SC](https://steamdb.info/depot/1760692/)
* [1760693 - TC](https://steamdb.info/depot/1760693/)
* [1855001 - NOeSIS Ⅱ-人生无常 Playtest Content](https://steamdb.info/depot/1855001/)
* [2106821 - ](https://steamdb.info/depot/2106821/)
* [2106822 - ](https://steamdb.info/depot/2106822/)
* [2106823 - ](https://steamdb.info/depot/2106823/)

**Comment by andOlga** [comment]
Sorry, I'm not entirely sure what to do with that list you posted.

The list of files I provided is based off my familiarity with the engine, as I've had the displeasure of working with it for quite a while. The only thing I can tell that's wrong (?) just by looking at this list is that none of the games *released on Steam* use the `ons.cfg` file, and very few use `pns.cfg` (and those fall into one of the other categories), but I wanted to account for possible future games as well.

**Comment by xPaw** [comment]
The list shows which games match particular files. It seems to me that you can reduce the list of files needed to match. Since you say the engine is old, I don't think there's a good reason to future proof it.

**Comment by andOlga** [comment]
Alright, I took out the least common files which matched games that also fell in the other categories, leaving us with just `arc.nsa` and `nscript.dat`. It should still match all of the games currently on Steam, at least.

**Pull request merged**
