### PR TITLE
Sciter

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/236390/
https://steamdb.info/app/884660/
https://steamdb.info/app/1275210/

### Brief explanation of the change
find the dll for Sciter, an embeddable HTML/CSS/script UI engine for modern desktop applications.

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.Sciter**

These apps now match: **(4)** [236390](https://steamdb.info/app/236390/depots/) [386180](https://steamdb.info/app/386180/depots/) [884660](https://steamdb.info/app/884660/depots/) [1923640](https://steamdb.info/app/1923640/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
not used by enough apps

**Pull request closed without merging**
