### PR TITLE
Improve GoldSource engine detection by searching for vgui.dll

### LINKED ISSUE #472: Counter-Strike Nexon: Studio - Undetected
### SteamDB link to the game

https://steamdb.info/app/273110/

### What should it be detected as?

Engine.GoldSource

### PR DESCRIPTION
**Pull request by tschumann**
### SteamDB app page links to a few games using this

- https://steamdb.info/app/273110/
- https://steamdb.info/app/225840/

### Brief explanation of the change

Engine.GoldSource works by looking for hltv.exe which isn't present in some engine branches, but vgui.dll is still present.

Fixes #472
Fixes #159

### CODE REVIEW

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.GoldSource**

**22** apps still match.

These apps now match: **(5)** [225840](https://steamdb.info/app/225840/depots/) [276060](https://steamdb.info/app/276060/depots/) [812440](https://steamdb.info/app/812440/depots/) [1283930](https://steamdb.info/app/1283930/depots/) [1908720](https://steamdb.info/app/1908720/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
For Counter-Strike Nexon, vgui.dll isn't at the root of the depot, it's in a subfolder, you need to adapt your regex for it to match that game

**Comment by tschumann** [comment]
Yep right you are - fixed.

**Comment by xPaw** [comment]
Why not remove hltv.exe then?

**Comment by tschumann** [comment]
Done. Is there a way to retrigger Wendy or will it only comment if there's a change?

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.GoldSource**

**22** apps still match.

These apps now match: **(8)** [225840](https://steamdb.info/app/225840/depots/) [273110](https://steamdb.info/app/273110/depots/) [276060](https://steamdb.info/app/276060/depots/) [668320](https://steamdb.info/app/668320/depots/) [812440](https://steamdb.info/app/812440/depots/) [1283930](https://steamdb.info/app/1283930/depots/) [1298760](https://steamdb.info/app/1298760/depots/) [1908720](https://steamdb.info/app/1908720/depots/)

Please confirm that all these changed apps are correct.

**Comment by tschumann** [comment]
Hm, bad match on Perilous Warp now - I will do some more digging.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.GoldSource**

**22** apps still match.

These apps now match: **(6)** [225840](https://steamdb.info/app/225840/depots/) [273110](https://steamdb.info/app/273110/depots/) [276060](https://steamdb.info/app/276060/depots/) [812440](https://steamdb.info/app/812440/depots/) [1283930](https://steamdb.info/app/1283930/depots/) [1908720](https://steamdb.info/app/1908720/depots/)

Please confirm that all these changed apps are correct.

**Comment by tschumann** [comment]
There we go - matches Counter-Strike: Nexon Studio, Sven Co-op and a few other Half-Life mods now.

**Pull request merged**
