### PR TITLE
Add Asura

### LINKED ISSUE #189: Add Asura detection
### Some reference to the engine, such as the developer site or a wikipedia article.

In-house Rebellion (Sniper Elite devs) engine, could only find wikipedia article on russian so i ran link through google translate (https://ru-m-wikipedia-org.translate.goog/wiki/Asura_(%D0%B8%D0%B3%D1%80%D0%BE%D0%B2%D0%BE%D0%B9_%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA)?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp) / https://ru.wikipedia.org/wiki/Asura_(%D0%B8%D0%B3%D1%80%D0%BE%D0%B2%D0%BE%D0%B9_%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA)

### SteamDB links

https://steamdb.info/app/3710/
https://steamdb.info/app/3700/
https://steamdb.info/app/7020/
https://steamdb.info/app/8160/
https://steamdb.info/app/22310/
https://steamdb.info/app/10680/
https://steamdb.info/app/63380/
https://steamdb.info/app/227100/
https://steamdb.info/app/247910/
https://steamdb.info/app/238090/
https://steamdb.info/app/301640/
https://steamdb.info/app/312660/
https://steamdb.info/app/700600/
https://steamdb.info/app/1029690/

### Possible way to detect it

not sure

### PR DESCRIPTION
**Pull request by Lifeismana**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1029690/
https://steamdb.info/app/3700/
https://steamdb.info/app/238090/
### Brief explanation of the change
Add Asura as an Engine
Sadly, i wasn't able to find any website to add as a link and it doesn't seem like the engine has a wikipedia page
closes #189

### CODE REVIEW

**Comment by diedyesterdaywashere** [comment]
#189?

**Comment by diedyesterdaywashere** [comment]
hmm, not merged yet...

**Comment by diedyesterdaywashere** [comment]
i think i added a link to russian wikipedia page about this engine and also added a link ran through google translate so there is actually a link

**Comment by Lifeismana** [comment]
Russian isn't english

**Comment by diedyesterdaywashere** [comment]
> Russian isn't english

yep, but as i said i also linked google translate link that redirects you to that page but in english

**Comment by diedyesterdaywashere** [comment]
> > Russian isn't english
> 
> yep, but as i said i also linked google translate link that redirects you to that page but in english

image
this big thing, if you want you can go run it through google translate for yourself, since i also linked original link

**Pull request merged**
