### PR TITLE
Add Discord Integration

### PR DESCRIPTION
**Pull request by Lifeismana**
`(?:^|/)discord-rpc\.dll$`
`(?:^|/)discord_game_sdk\.dll$`
There is probably a way to make the name clearer and the description better, i though about simply calling it Discord but i think it's weird.
From my small search, the game [Move or Die](https://steamdb.info/app/323850/) has the dll renamed in `discord.dll` but i'm not sure if it's worth it to add that name as a rule

### CODE REVIEW

**Comment by xPaw** [comment]
I'd probably just call this `Discord`.

**Comment by Lifeismana** [comment]
I first though on doing so but starting the description with `Discord is ....` really seems weird to me, it seems like we are talking about the app and not the integration so that why i choose that name

**Comment by xPaw** [comment]
Well description can be more descriptive.

**Comment by Lifeismana** [comment]
This should be good now!

**Pull request closed without merging**
