### PR TITLE
GB Studio

### LINKED ISSUE #291: Add GB Studio
### Some reference to the engine, such as the developer site or a wikipedia article.

https://www.gbstudio.dev/

### SteamDB links

https://steamdb.info/app/1502250

### Possible way to detect it

_No response_

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### Brief explanation of the change
closes #291

### CODE REVIEW

**Comment by andOlga** [comment]
This would detect any GameBoy ROM. Not every GameBoy game is made in GB Studio.

**Comment by diedyesterdaywashere** [comment]
> This would detect any GameBoy ROM. Not every GameBoy game is made in GB Studio.

tbh i don't think steam depots have gameboy games, but who knows... 👀

**Comment by andOlga** [comment]
> (by that i meant like original roms, that aren't made in any software like gb studio)

Obviously any GameBoy stuff released on Steam is going to be homebrew, but there is no guarantee that all of it is going to be made *specifically* in GB Studio, especially in the future (I'm not able to analyze the current state of Steam to see whether this is *currently* the case, but this should not be relevant).

If we are to detect ROM formats for emulated games, that *could* be useful for finding this sort of homebrew stuff, but I think it should be its own category, not lumped together with engines.

**Comment by diedyesterdaywashere** [comment]
we can also probably just fix it later using custom php logic to differenciate gb games, but for now as we don't know any other gameboy game makers it *should* be fine?

**Comment by Lifeismana** [comment]
there's no depots with a file ending with .gbsproj 
here's the depots with a file ending with .gb :

* [475101 - Kalonline Content](https://steamdb.info/depot/475101/)
* [700101 - Spooky Station](https://steamdb.info/depot/700101/)
* [727431 - Starcaster Content](https://steamdb.info/depot/727431/) (this depot is linked  to no apps and the app named Starcaster was retired)
* [781271 - Chaos Control Content](https://steamdb.info/depot/781271/)
* [1025271 - Nogalious MSX Content](https://steamdb.info/depot/1025271/)
* [1684991 - ](https://steamdb.info/depot/1684991/)
* [2061141 - ](https://steamdb.info/depot/2061141/)
* [2198981 - ](https://steamdb.info/depot/2198981/)
* [2200691 - ](https://steamdb.info/depot/2200691/)
* [2244571 - ](https://steamdb.info/depot/2244571/)
* [2293662 - ](https://steamdb.info/depot/2293662/)
* [2446561 - ](https://steamdb.info/depot/2446561/)
* [2462261 - ](https://steamdb.info/depot/2462261/)

**Comment by MichaelHinrichs** [comment]
Fuck it, I give up.

**Pull request closed without merging**
