### PR TITLE
Add Orx

### LINKED ISSUE #76: Engine: orx
### Some reference to the engine, such as the developer site or a wikipedia article.

Orx is an open source (zlib license), heavily data-driven, lightweight, cross-platform 2D game engine written in C.
It currently supports Windows, Linux, MacOS, iOS and Android.

Home page: https://orx-project.org
Github repository: https://github.com/orx/orx
Wikipedia page: https://en.wikipedia.org/wiki/ORX

### SteamDB links

As far as I know, so far there's only a single game made with orx that has been published on Steam (I was part of the dev team):

https://steamdb.info/app/352210/

### Possible way to detect it

The engine is always contained inside a single file. Its name depends on the target platform:

- orx.dll on Windows
- liborx.so on Linux
- liborx.dylib on MacOS

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

https://steamdb.info/app/352210/

### Brief explanation of the change

closes #76
Added a rule for orx engine

### CODE REVIEW

**Comment by Lifeismana** [comment]
Can you capitalize the first letter of the rule name (& make the adequate changes in filenames)

**Comment by diedyesterdaywashere** [comment]
>(& make the adequate changes in filenames)

Hm?

**Comment by Lifeismana** [comment]
`descriptions/Engine.orx.md` => `descriptions/Engine.Orx.md`

**Comment by diedyesterdaywashere** [comment]
ah

**Comment by diedyesterdaywashere** [comment]
for some reason github desktop didnt want to pick up me changing orx to Orx?

**Comment by diedyesterdaywashere** [comment]
had to use github website to change file names since github desktop didnt care about lettercase changes for some reason

**Comment by Lifeismana** [comment]
This is a engine that has only has one game (and a demo) so i won't merge this but we can switch this to a draft
https://steamdb.info/app/352210/
https://steamdb.info/app/2268640/

Also you can just check for `orx.dll`

**Pull request closed without merging**
