### PR TITLE
Add CRIWARE

### PR DESCRIPTION
**Pull request by M00nG**
### SteamDB app page links to a few games using this

[TEKKEN 7](https://steamdb.info/app/389730/)
[NieR:Automata™](https://steamdb.info/app/524220/)
[DRAGON BALL Z: KAKAROT](https://steamdb.info/app/851850/)

### Brief explanation of the change

CRIWARE is integrated in executable, so there is no library files

### CODE REVIEW

**Comment by larsiusprime** [comment]
Your rule is:
```ini
CRIWARE = (?:^|/|\.)(?:cpk|sfd|usm|adx|acb|awb)$
```

Two things:

1. You have the dot in the wrong space. It should be 
```ini
CRIWARE = (?:^|/)\.(?:cpk|sfd|usm|adx|acb|awb)$
```
2. You are checking for a LOT of different file extensions, which could really cause many false positives. From what I can tell all of the examples you gave all have at least one `.usm` file and that alone would be sufficient. Do you have other examples that do not have `.usm` files and need to match one of these other ones?

**Comment by M00nG** [comment]
but change rule, doesn't detect it.

**Comment by Lifeismana** [comment]
For XNA, we are looking for a folder which is not the case here.
Since, we are only looking at file extension for this one, you can even simplify your regex a bit more, like so:
```ini
CRIWARE = \.(?:cpk|sfd|usm|adx|acb|awb)$
```

But as lars said, in exemples you gave, these game all have in common the .usm file ext, couldn't that be enough to find CRIWARE game ? 
If in the end it's enough, you can even more simplify your regex:
```ini
CRIWARE = \.usm$
```

**Comment by M00nG** [comment]
However, the .usm you mentioned is only a video file from CRIWARE. CRIWARE is middleware with video/audio/packaging. Therefore, since each extension exists, only .usm is not CRIWARE. (However, since most Japanese developers currently use Unreal, they often use only .usm) 
.cpk is pakage file for CRIWARE from [**NieR:Automata™**](https://steamdb.info/app/524220/), [**NARUTO SHIPPUDEN: Ultimate Ninja STORM 4**](https://steamdb.info/app/349040/depots/) and [**DRAGON BALL XENOVERSE 2**](https://steamdb.info/app/454650/)
.adx and .sfd is old version of CRIWARE's audio and video file on [**Sonic Adventure DX**](https://steamdb.info/app/71250) and many PS1~PS2 area games
.acb and .awb is audio file for CRIWARE from [**DAEMON X MACHINA**](https://steamdb.info/app/1167450/) and [**Life is Strange: Before the Storm**](https://steamdb.info/app/554620/)

**Comment by M00nG** [comment]
fixed it, but there was a problem.
it seems that information about id Tech 7 (used by DOOM Eternal) is missing, so it should be added. (but idk what the files are only in DOOM Eternal)

**Comment by Lifeismana** [comment]
This error was resolved on the main branch, rebase your PR to make it disappear

**Comment by M00nG** [comment]
Updated.

**Comment by M00nG** [comment]
I'm Sorry but it seems my PR is being ignored.

**Comment by xPaw** [comment]
Please look through https://steamdb.info/tech/SDK/CRIWARE/

**Pull request merged**
