### PR TITLE
Add SharpDX

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/244850/
https://steamdb.info/app/287630/
https://steamdb.info/app/300610/
https://steamdb.info/app/333950/
https://steamdb.info/app/367030/
https://steamdb.info/app/509020/
https://steamdb.info/app/527240/
https://steamdb.info/app/542480/
https://steamdb.info/app/550200/
https://steamdb.info/app/564080/
https://steamdb.info/app/565640/
https://steamdb.info/app/595520/
https://steamdb.info/app/622510/
https://steamdb.info/app/652560/
https://steamdb.info/app/661500/
https://steamdb.info/app/672730/
https://steamdb.info/app/685420/
https://steamdb.info/app/758870/
https://steamdb.info/app/768970/
https://steamdb.info/app/851790/
https://steamdb.info/app/893970/
https://steamdb.info/app/933290/
https://steamdb.info/app/1026680/
https://steamdb.info/app/1029500/
https://steamdb.info/app/1085660/
https://steamdb.info/app/1178030/
https://steamdb.info/app/1193550/
https://steamdb.info/app/1275670/
https://steamdb.info/app/1328780/
https://steamdb.info/app/1373440/
https://steamdb.info/app/1436190/
https://steamdb.info/app/1454690/
https://steamdb.info/app/1466950/
https://steamdb.info/app/1617580/
https://steamdb.info/app/1618450/
https://steamdb.info/app/1882140/
https://steamdb.info/app/1895130/
https://steamdb.info/app/1966500/
https://steamdb.info/app/2060550/
https://steamdb.info/app/2116280/
https://steamdb.info/app/2196300/
https://steamdb.info/app/2349480/

### Brief explanation of the change
Find SharpDX libraries.

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.SharpDX**

These apps now match: **(435)** [57650](https://steamdb.info/app/57650/depots/) [200550](https://steamdb.info/app/200550/depots/) [201060](https://steamdb.info/app/201060/depots/) [223430](https://steamdb.info/app/223430/depots/) [223490](https://steamdb.info/app/223490/depots/) [226240](https://steamdb.info/app/226240/depots/) [227800](https://steamdb.info/app/227800/depots/) [233630](https://steamdb.info/app/233630/depots/) [234670](https://steamdb.info/app/234670/depots/) [238530](https://steamdb.info/app/238530/depots/) [244850](https://steamdb.info/app/244850/depots/) [251470](https://steamdb.info/app/251470/depots/) [257750](https://steamdb.info/app/257750/depots/) [263200](https://steamdb.info/app/263200/depots/) [272510](https://steamdb.info/app/272510/depots/) [277930](https://steamdb.info/app/277930/depots/) [284100](https://steamdb.info/app/284100/depots/) [286000](https://steamdb.info/app/286000/depots/) [286880](https://steamdb.info/app/286880/depots/) [287630](https://steamdb.info/app/287630/depots/) [287840](https://steamdb.info/app/287840/depots/) [296050](https://steamdb.info/app/296050/depots/) [298740](https://steamdb.info/app/298740/depots/) [300610](https://steamdb.info/app/300610/depots/) [300630](https://steamdb.info/app/300630/depots/) [301830](https://steamdb.info/app/301830/depots/) [307150](https://steamdb.info/app/307150/depots/) [310760](https://steamdb.info/app/310760/depots/) [311410](https://steamdb.info/app/311410/depots/) [313470](https://steamdb.info/app/313470/depots/) [315340](https://steamdb.info/app/315340/depots/) [319210](https://steamdb.info/app/319210/depots/) [321010](https://steamdb.info/app/321010/depots/) [322540](https://steamdb.info/app/322540/depots/) [322950](https://steamdb.info/app/322950/depots/) [326220](https://steamdb.info/app/326220/depots/) [326880](https://steamdb.info/app/326880/depots/) [331290](https://steamdb.info/app/331290/depots/) [332370](https://steamdb.info/app/332370/depots/) [333950](https://steamdb.info/app/333950/depots/) [334560](https://steamdb.info/app/334560/depots/) [340210](https://steamdb.info/app/340210/depots/) [341570](https://steamdb.info/app/341570/depots/) [344780](https://steamdb.info/app/344780/depots/) [347940](https://steamdb.info/app/347940/depots/) [349110](https://steamdb.info/app/349110/depots/) [351230](https://steamdb.info/app/351230/depots/) [354040](https://steamdb.info/app/354040/depots/) [360430](https://steamdb.info/app/360430/depots/) [360580](https://steamdb.info/app/360580/depots/) [361230](https://steamdb.info/app/361230/depots/) [362350](https://steamdb.info/app/362350/depots/) [365000](https://steamdb.info/app/365000/depots/) [367030](https://steamdb.info/app/367030/depots/) [367970](https://steamdb.info/app/367970/depots/) [371700](https://steamdb.info/app/371700/depots/) [372430](https://steamdb.info/app/372430/depots/) [379610](https://steamdb.info/app/379610/depots/) [380540](https://steamdb.info/app/380540/depots/) [381220](https://steamdb.info/app/381220/depots/) [382110](https://steamdb.info/app/382110/depots/) [388980](https://steamdb.info/app/388980/depots/) [389170](https://steamdb.info/app/389170/depots/) [392040](https://steamdb.info/app/392040/depots/) [392080](https://steamdb.info/app/392080/depots/) [393600](https://steamdb.info/app/393600/depots/) [395900](https://steamdb.info/app/395900/depots/) [396700](https://steamdb.info/app/396700/depots/) [403680](https://steamdb.info/app/403680/depots/) [404350](https://steamdb.info/app/404350/depots/) [405710](https://steamdb.info/app/405710/depots/) [410560](https://steamdb.info/app/410560/depots/) [417900](https://steamdb.info/app/417900/depots/) [423220](https://steamdb.info/app/423220/depots/) [427910](https://steamdb.info/app/427910/depots/) [429430](https://steamdb.info/app/429430/depots/) [430440](https://steamdb.info/app/430440/depots/) [440120](https://steamdb.info/app/440120/depots/) [447950](https://steamdb.info/app/447950/depots/) [448620](https://steamdb.info/app/448620/depots/) [453300](https://steamdb.info/app/453300/depots/) [455490](https://steamdb.info/app/455490/depots/) [457000](https://steamdb.info/app/457000/depots/) [459580](https://steamdb.info/app/459580/depots/) [459830](https://steamdb.info/app/459830/depots/) [474620](https://steamdb.info/app/474620/depots/) [485620](https://steamdb.info/app/485620/depots/) [485900](https://steamdb.info/app/485900/depots/) [488080](https://steamdb.info/app/488080/depots/) [490880](https://steamdb.info/app/490880/depots/) [506860](https://steamdb.info/app/506860/depots/) [509020](https://steamdb.info/app/509020/depots/) [513440](https://steamdb.info/app/513440/depots/) [515040](https://steamdb.info/app/515040/depots/) [516860](https://steamdb.info/app/516860/depots/) [517160](https://steamdb.info/app/517160/depots/) [519050](https://steamdb.info/app/519050/depots/) [524860](https://steamdb.info/app/524860/depots/) [525380](https://steamdb.info/app/525380/depots/) [527240](https://steamdb.info/app/527240/depots/) [542480](https://steamdb.info/app/542480/depots/) [542680](https://steamdb.info/app/542680/depots/) [543010](https://steamdb.info/app/543010/depots/) [549390](https://steamdb.info/app/549390/depots/) [550200](https://steamdb.info/app/550200/depots/) [552780](https://steamdb.info/app/552780/depots/) [563390](https://steamdb.info/app/563390/depots/) [563570](https://steamdb.info/app/563570/depots/) [564080](https://steamdb.info/app/564080/depots/) [565640](https://steamdb.info/app/565640/depots/) [569350](https://steamdb.info/app/569350/depots/) [577470](https://steamdb.info/app/577470/depots/) [587470](https://steamdb.info/app/587470/depots/) [591910](https://steamdb.info/app/591910/depots/) [593490](https://steamdb.info/app/593490/depots/) [595520](https://steamdb.info/app/595520/depots/) [599040](https://steamdb.info/app/599040/depots/) [600160](https://steamdb.info/app/600160/depots/) [602960](https://steamdb.info/app/602960/depots/) [607880](https://steamdb.info/app/607880/depots/) [622510](https://steamdb.info/app/622510/depots/) [624780](https://steamdb.info/app/624780/depots/) [640290](https://steamdb.info/app/640290/depots/) [645370](https://steamdb.info/app/645370/depots/) [645720](https://steamdb.info/app/645720/depots/) [652560](https://steamdb.info/app/652560/depots/) [653870](https://steamdb.info/app/653870/depots/) [655020](https://steamdb.info/app/655020/depots/) [661500](https://steamdb.info/app/661500/depots/) [662930](https://steamdb.info/app/662930/depots/) [665640](https://steamdb.info/app/665640/depots/) [672410](https://steamdb.info/app/672410/depots/) [672730](https://steamdb.info/app/672730/depots/) [685420](https://steamdb.info/app/685420/depots/) [685700](https://steamdb.info/app/685700/depots/) [687550](https://steamdb.info/app/687550/depots/) [690560](https://steamdb.info/app/690560/depots/) [693750](https://steamdb.info/app/693750/depots/) [701880](https://steamdb.info/app/701880/depots/) [704570](https://steamdb.info/app/704570/depots/) [714030](https://steamdb.info/app/714030/depots/) [719950](https://steamdb.info/app/719950/depots/) [725120](https://steamdb.info/app/725120/depots/) [727290](https://steamdb.info/app/727290/depots/) [727570](https://steamdb.info/app/727570/depots/) [734090](https://steamdb.info/app/734090/depots/) [740250](https://steamdb.info/app/740250/depots/) [749720](https://steamdb.info/app/749720/depots/) [758330](https://steamdb.info/app/758330/depots/) [758870](https://steamdb.info/app/758870/depots/) [760960](https://steamdb.info/app/760960/depots/) [768970](https://steamdb.info/app/768970/depots/) [770630](https://steamdb.info/app/770630/depots/) [772450](https://steamdb.info/app/772450/depots/) [776660](https://steamdb.info/app/776660/depots/) [787810](https://steamdb.info/app/787810/depots/) [789580](https://steamdb.info/app/789580/depots/) [792550](https://steamdb.info/app/792550/depots/) [799600](https://steamdb.info/app/799600/depots/) [802270](https://steamdb.info/app/802270/depots/) [803350](https://steamdb.info/app/803350/depots/) [808800](https://steamdb.info/app/808800/depots/) [809670](https://steamdb.info/app/809670/depots/) [809860](https://steamdb.info/app/809860/depots/) [811160](https://steamdb.info/app/811160/depots/) [812960](https://steamdb.info/app/812960/depots/) [813730](https://steamdb.info/app/813730/depots/) [814560](https://steamdb.info/app/814560/depots/) [821490](https://steamdb.info/app/821490/depots/) [822810](https://steamdb.info/app/822810/depots/) [822820](https://steamdb.info/app/822820/depots/) [827200](https://steamdb.info/app/827200/depots/) [829590](https://steamdb.info/app/829590/depots/) [831910](https://steamdb.info/app/831910/depots/) [839520](https://steamdb.info/app/839520/depots/) [841580](https://steamdb.info/app/841580/depots/) [841600](https://steamdb.info/app/841600/depots/) [847520](https://steamdb.info/app/847520/depots/) [847780](https://steamdb.info/app/847780/depots/) [851790](https://steamdb.info/app/851790/depots/) [863150](https://steamdb.info/app/863150/depots/) [877550](https://steamdb.info/app/877550/depots/) [889790](https://steamdb.info/app/889790/depots/) [893970](https://steamdb.info/app/893970/depots/) [906310](https://steamdb.info/app/906310/depots/) [907940](https://steamdb.info/app/907940/depots/) [908520](https://steamdb.info/app/908520/depots/) [910370](https://steamdb.info/app/910370/depots/) [911170](https://steamdb.info/app/911170/depots/) [923540](https://steamdb.info/app/923540/depots/) [929850](https://steamdb.info/app/929850/depots/) [933290](https://steamdb.info/app/933290/depots/) [933580](https://steamdb.info/app/933580/depots/) [934120](https://steamdb.info/app/934120/depots/) [934480](https://steamdb.info/app/934480/depots/) [940020](https://steamdb.info/app/940020/depots/) [946030](https://steamdb.info/app/946030/depots/) [959730](https://steamdb.info/app/959730/depots/) [968590](https://steamdb.info/app/968590/depots/) [980630](https://steamdb.info/app/980630/depots/) [980770](https://steamdb.info/app/980770/depots/) [982670](https://steamdb.info/app/982670/depots/) [1000880](https://steamdb.info/app/1000880/depots/) [1009280](https://steamdb.info/app/1009280/depots/) [1009940](https://steamdb.info/app/1009940/depots/) [1020480](https://steamdb.info/app/1020480/depots/) [1023860](https://steamdb.info/app/1023860/depots/) [1026680](https://steamdb.info/app/1026680/depots/) [1028360](https://steamdb.info/app/1028360/depots/) [1029500](https://steamdb.info/app/1029500/depots/) [1030830](https://steamdb.info/app/1030830/depots/) [1030840](https://steamdb.info/app/1030840/depots/) [1034930](https://steamdb.info/app/1034930/depots/) [1036640](https://steamdb.info/app/1036640/depots/) [1040750](https://steamdb.info/app/1040750/depots/) [1049340](https://steamdb.info/app/1049340/depots/) [1049500](https://steamdb.info/app/1049500/depots/) [1061090](https://steamdb.info/app/1061090/depots/) [1061720](https://steamdb.info/app/1061720/depots/) [1068820](https://steamdb.info/app/1068820/depots/) [1070980](https://steamdb.info/app/1070980/depots/) [1074150](https://steamdb.info/app/1074150/depots/) [1076030](https://steamdb.info/app/1076030/depots/) [1081420](https://steamdb.info/app/1081420/depots/) [1081700](https://steamdb.info/app/1081700/depots/) [1085660](https://steamdb.info/app/1085660/depots/) [1087630](https://steamdb.info/app/1087630/depots/) [1092160](https://steamdb.info/app/1092160/depots/) [1105160](https://steamdb.info/app/1105160/depots/) [1110960](https://steamdb.info/app/1110960/depots/) [1111230](https://steamdb.info/app/1111230/depots/) [1112510](https://steamdb.info/app/1112510/depots/) [1122930](https://steamdb.info/app/1122930/depots/) [1127310](https://steamdb.info/app/1127310/depots/) [1143570](https://steamdb.info/app/1143570/depots/) [1154840](https://steamdb.info/app/1154840/depots/) [1164320](https://steamdb.info/app/1164320/depots/) [1165740](https://steamdb.info/app/1165740/depots/) [1174450](https://steamdb.info/app/1174450/depots/) [1178030](https://steamdb.info/app/1178030/depots/) [1178420](https://steamdb.info/app/1178420/depots/) [1188920](https://steamdb.info/app/1188920/depots/) [1193550](https://steamdb.info/app/1193550/depots/) [1194170](https://steamdb.info/app/1194170/depots/) [1199570](https://steamdb.info/app/1199570/depots/) [1202860](https://steamdb.info/app/1202860/depots/) [1220510](https://steamdb.info/app/1220510/depots/) [1226760](https://steamdb.info/app/1226760/depots/) [1232260](https://steamdb.info/app/1232260/depots/) [1235770](https://steamdb.info/app/1235770/depots/) [1242710](https://steamdb.info/app/1242710/depots/) [1243360](https://steamdb.info/app/1243360/depots/) [1245410](https://steamdb.info/app/1245410/depots/) [1249890](https://steamdb.info/app/1249890/depots/) [1256380](https://steamdb.info/app/1256380/depots/) [1258520](https://steamdb.info/app/1258520/depots/) [1264790](https://steamdb.info/app/1264790/depots/) [1268830](https://steamdb.info/app/1268830/depots/) [1272580](https://steamdb.info/app/1272580/depots/) [1273870](https://steamdb.info/app/1273870/depots/) [1275670](https://steamdb.info/app/1275670/depots/) [1282070](https://steamdb.info/app/1282070/depots/) [1283440](https://steamdb.info/app/1283440/depots/) [1289750](https://steamdb.info/app/1289750/depots/) [1299900](https://steamdb.info/app/1299900/depots/) [1304570](https://steamdb.info/app/1304570/depots/) [1310220](https://steamdb.info/app/1310220/depots/) [1323650](https://steamdb.info/app/1323650/depots/) [1323690](https://steamdb.info/app/1323690/depots/) [1323700](https://steamdb.info/app/1323700/depots/) [1328780](https://steamdb.info/app/1328780/depots/) [1339310](https://steamdb.info/app/1339310/depots/) [1348520](https://steamdb.info/app/1348520/depots/) [1364470](https://steamdb.info/app/1364470/depots/) [1373440](https://steamdb.info/app/1373440/depots/) [1380360](https://steamdb.info/app/1380360/depots/) [1403560](https://steamdb.info/app/1403560/depots/) [1405160](https://steamdb.info/app/1405160/depots/) [1406150](https://steamdb.info/app/1406150/depots/) [1408420](https://steamdb.info/app/1408420/depots/) [1409760](https://steamdb.info/app/1409760/depots/) [1409810](https://steamdb.info/app/1409810/depots/) [1415320](https://steamdb.info/app/1415320/depots/) [1418100](https://steamdb.info/app/1418100/depots/) [1422180](https://steamdb.info/app/1422180/depots/) [1430320](https://steamdb.info/app/1430320/depots/) [1436190](https://steamdb.info/app/1436190/depots/) [1437400](https://steamdb.info/app/1437400/depots/) [1441630](https://steamdb.info/app/1441630/depots/) [1443760](https://steamdb.info/app/1443760/depots/) [1454690](https://steamdb.info/app/1454690/depots/) [1466950](https://steamdb.info/app/1466950/depots/) [1471890](https://steamdb.info/app/1471890/depots/) [1473840](https://steamdb.info/app/1473840/depots/) [1475690](https://steamdb.info/app/1475690/depots/) [1484980](https://steamdb.info/app/1484980/depots/) [1487640](https://steamdb.info/app/1487640/depots/) [1491460](https://steamdb.info/app/1491460/depots/) [1494500](https://steamdb.info/app/1494500/depots/) [1505640](https://steamdb.info/app/1505640/depots/) [1512190](https://steamdb.info/app/1512190/depots/) [1521560](https://steamdb.info/app/1521560/depots/) [1531540](https://steamdb.info/app/1531540/depots/) [1541840](https://steamdb.info/app/1541840/depots/) [1544740](https://steamdb.info/app/1544740/depots/) [1547890](https://steamdb.info/app/1547890/depots/) [1556740](https://steamdb.info/app/1556740/depots/) [1588990](https://steamdb.info/app/1588990/depots/) [1590060](https://steamdb.info/app/1590060/depots/) [1593280](https://steamdb.info/app/1593280/depots/) [1596890](https://steamdb.info/app/1596890/depots/) [1612770](https://steamdb.info/app/1612770/depots/) [1617580](https://steamdb.info/app/1617580/depots/) [1618450](https://steamdb.info/app/1618450/depots/) [1619550](https://steamdb.info/app/1619550/depots/) [1636240](https://steamdb.info/app/1636240/depots/) [1638260](https://steamdb.info/app/1638260/depots/) [1663670](https://steamdb.info/app/1663670/depots/) [1674160](https://steamdb.info/app/1674160/depots/) [1676110](https://steamdb.info/app/1676110/depots/) [1694700](https://steamdb.info/app/1694700/depots/) [1702430](https://steamdb.info/app/1702430/depots/) [1733990](https://steamdb.info/app/1733990/depots/) [1737130](https://steamdb.info/app/1737130/depots/) [1760390](https://steamdb.info/app/1760390/depots/) [1770440](https://steamdb.info/app/1770440/depots/) [1799670](https://steamdb.info/app/1799670/depots/) [1811950](https://steamdb.info/app/1811950/depots/) [1855200](https://steamdb.info/app/1855200/depots/) [1855400](https://steamdb.info/app/1855400/depots/) [1868400](https://steamdb.info/app/1868400/depots/) [1881240](https://steamdb.info/app/1881240/depots/) [1882140](https://steamdb.info/app/1882140/depots/) [1888920](https://steamdb.info/app/1888920/depots/) [1891060](https://steamdb.info/app/1891060/depots/) [1895130](https://steamdb.info/app/1895130/depots/) [1909470](https://steamdb.info/app/1909470/depots/) [1915930](https://steamdb.info/app/1915930/depots/) [1919890](https://steamdb.info/app/1919890/depots/) [1941690](https://steamdb.info/app/1941690/depots/) [1948540](https://steamdb.info/app/1948540/depots/) [1963870](https://steamdb.info/app/1963870/depots/) [1966500](https://steamdb.info/app/1966500/depots/) [1968500](https://steamdb.info/app/1968500/depots/) [1980970](https://steamdb.info/app/1980970/depots/) [1991420](https://steamdb.info/app/1991420/depots/) [1994300](https://steamdb.info/app/1994300/depots/) [1996880](https://steamdb.info/app/1996880/depots/) [2000760](https://steamdb.info/app/2000760/depots/) [2001910](https://steamdb.info/app/2001910/depots/) [2027620](https://steamdb.info/app/2027620/depots/) [2051930](https://steamdb.info/app/2051930/depots/) [2053500](https://steamdb.info/app/2053500/depots/) [2053580](https://steamdb.info/app/2053580/depots/) [2056780](https://steamdb.info/app/2056780/depots/) [2060550](https://steamdb.info/app/2060550/depots/) [2069150](https://steamdb.info/app/2069150/depots/) [2083100](https://steamdb.info/app/2083100/depots/) [2109710](https://steamdb.info/app/2109710/depots/) [2110380](https://steamdb.info/app/2110380/depots/) [2113920](https://steamdb.info/app/2113920/depots/) [2116280](https://steamdb.info/app/2116280/depots/) [2117440](https://steamdb.info/app/2117440/depots/) [2137590](https://steamdb.info/app/2137590/depots/) [2140380](https://steamdb.info/app/2140380/depots/) [2141100](https://steamdb.info/app/2141100/depots/) [2147400](https://steamdb.info/app/2147400/depots/) [2149170](https://steamdb.info/app/2149170/depots/) [2186670](https://steamdb.info/app/2186670/depots/) [2196300](https://steamdb.info/app/2196300/depots/) [2206820](https://steamdb.info/app/2206820/depots/) [2211960](https://steamdb.info/app/2211960/depots/) [2215670](https://steamdb.info/app/2215670/depots/) [2221440](https://steamdb.info/app/2221440/depots/) [2245910](https://steamdb.info/app/2245910/depots/) [2251760](https://steamdb.info/app/2251760/depots/) [2279940](https://steamdb.info/app/2279940/depots/) [2296910](https://steamdb.info/app/2296910/depots/) [2300970](https://steamdb.info/app/2300970/depots/) [2308910](https://steamdb.info/app/2308910/depots/) [2326510](https://steamdb.info/app/2326510/depots/) [2326780](https://steamdb.info/app/2326780/depots/) [2338630](https://steamdb.info/app/2338630/depots/) [2338690](https://steamdb.info/app/2338690/depots/) [2342580](https://steamdb.info/app/2342580/depots/) [2349480](https://steamdb.info/app/2349480/depots/) [2350010](https://steamdb.info/app/2350010/depots/) [2381160](https://steamdb.info/app/2381160/depots/) [2390110](https://steamdb.info/app/2390110/depots/) [2396700](https://steamdb.info/app/2396700/depots/) [2417490](https://steamdb.info/app/2417490/depots/) [2444290](https://steamdb.info/app/2444290/depots/) [2454060](https://steamdb.info/app/2454060/depots/) [2461400](https://steamdb.info/app/2461400/depots/) [2461410](https://steamdb.info/app/2461410/depots/) [2481230](https://steamdb.info/app/2481230/depots/) [2489420](https://steamdb.info/app/2489420/depots/) [2489650](https://steamdb.info/app/2489650/depots/) [2491380](https://steamdb.info/app/2491380/depots/) [2499210](https://steamdb.info/app/2499210/depots/) [2516360](https://steamdb.info/app/2516360/depots/) [2516610](https://steamdb.info/app/2516610/depots/) [2519830](https://steamdb.info/app/2519830/depots/) [2520760](https://steamdb.info/app/2520760/depots/) [2533180](https://steamdb.info/app/2533180/depots/) [2533260](https://steamdb.info/app/2533260/depots/) [2538150](https://steamdb.info/app/2538150/depots/) [2546770](https://steamdb.info/app/2546770/depots/) [2547550](https://steamdb.info/app/2547550/depots/) [2562350](https://steamdb.info/app/2562350/depots/) [2570810](https://steamdb.info/app/2570810/depots/) [2586680](https://steamdb.info/app/2586680/depots/) [2587880](https://steamdb.info/app/2587880/depots/) [2588570](https://steamdb.info/app/2588570/depots/) [2588630](https://steamdb.info/app/2588630/depots/) [2610370](https://steamdb.info/app/2610370/depots/) [2616350](https://steamdb.info/app/2616350/depots/) [2616360](https://steamdb.info/app/2616360/depots/) [2630390](https://steamdb.info/app/2630390/depots/) [2634720](https://steamdb.info/app/2634720/depots/) [2650840](https://steamdb.info/app/2650840/depots/) [2651950](https://steamdb.info/app/2651950/depots/) [2677750](https://steamdb.info/app/2677750/depots/) [2687670](https://steamdb.info/app/2687670/depots/) [2693730](https://steamdb.info/app/2693730/depots/) [2693810](https://steamdb.info/app/2693810/depots/) [2707970](https://steamdb.info/app/2707970/depots/) [2725700](https://steamdb.info/app/2725700/depots/) [2749740](https://steamdb.info/app/2749740/depots/) [2766070](https://steamdb.info/app/2766070/depots/) [2767480](https://steamdb.info/app/2767480/depots/) [2785810](https://steamdb.info/app/2785810/depots/) [2804320](https://steamdb.info/app/2804320/depots/) [2806500](https://steamdb.info/app/2806500/depots/) [2859120](https://steamdb.info/app/2859120/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
merged in c80efd3cb982a964d22518c8d5895ce475828720

**Pull request closed without merging**
