### PR TITLE
Torque forest files

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/391780/

### Brief explanation of the change
Detect Torque Engine by finding "forest" files.

### CODE REVIEW

**Comment by Lifeismana** [comment]
Can you check if these 3 games are using Torque Engine ?
https://steamdb.info/app/530560/info/
https://steamdb.info/app/346920/info/
https://steamdb.info/app/39620/info/

**Comment by MichaelHinrichs** [comment]
The third one doesn't have any forest files in it.

**Comment by Lifeismana** [comment]
it does `Locations/Exterior.Forest `

**Comment by MichaelHinrichs** [comment]
filetypes
What depot do you see this in?

**Comment by Lifeismana** [comment]
image

**Comment by MichaelHinrichs** [comment]
Those first two arn't forest files, and won't be picked up by the new rule in this pill request. The last one is a folder.

**Comment by Lifeismana** [comment]
a folder is still a file, it will get picked up

**Comment by MichaelHinrichs** [comment]
Dang it. I don't know what to do about that.

**Pull request closed without merging**
