### PR TITLE
Add MGame's Engine

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
- [Knight Online](https://steamdb.info/app/389430/)
- [Legend of Ares](https://steamdb.info/app/536950)
- [Hero Plus](https://steamdb.info/app/747920/)

### Brief explanation of the change
Find "n3" file types. Legend of Ares is not credited to MGame on Steam, but it's on MGame's websight.

### CODE REVIEW

**Comment by Lifeismana** [comment]
that regex is too big, reduce it

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.MGame**

These apps now match: **(3)** [389430](https://steamdb.info/app/389430/depots/) [536950](https://steamdb.info/app/536950/depots/) [747920](https://steamdb.info/app/747920/depots/)

Please confirm that all these changed apps are correct.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.MGame**

These apps now match: **(3)** [389430](https://steamdb.info/app/389430/depots/) [536950](https://steamdb.info/app/536950/depots/) [747920](https://steamdb.info/app/747920/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
not used by enough apps

**Pull request closed without merging**
