### PR TITLE
Add Sludge Engine

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/380140/

### Brief explanation of the change
Find SLUDGE from it's SLG file type.

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.SLUDGE**

These apps now match: **(9)** [6510](https://steamdb.info/app/6510/depots/) [6530](https://steamdb.info/app/6530/depots/) [6540](https://steamdb.info/app/6540/depots/) [6580](https://steamdb.info/app/6580/depots/) [6590](https://steamdb.info/app/6590/depots/) [21690](https://steamdb.info/app/21690/depots/) [45700](https://steamdb.info/app/45700/depots/) [45720](https://steamdb.info/app/45720/depots/) [380140](https://steamdb.info/app/380140/depots/)

Please confirm that all these changed apps are correct.

**Comment by MichaelHinrichs** [comment]
Never mind. All but 1 game are false positives. Not worth it.

**Pull request closed without merging**
