### PR TITLE
DevIL

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1342630/
https://steamdb.info/app/1476690/

### Brief explanation of the change
Find Developer's Image Library.

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.DevIL**

These apps now match: **(189)** [3230](https://steamdb.info/app/3230/depots/) [4540](https://steamdb.info/app/4540/depots/) [4550](https://steamdb.info/app/4550/depots/) [4590](https://steamdb.info/app/4590/depots/) [4900](https://steamdb.info/app/4900/depots/) [4910](https://steamdb.info/app/4910/depots/) [7860](https://steamdb.info/app/7860/depots/) [11250](https://steamdb.info/app/11250/depots/) [11260](https://steamdb.info/app/11260/depots/) [12340](https://steamdb.info/app/12340/depots/) [12440](https://steamdb.info/app/12440/depots/) [12450](https://steamdb.info/app/12450/depots/) [12660](https://steamdb.info/app/12660/depots/) [12810](https://steamdb.info/app/12810/depots/) [21300](https://steamdb.info/app/21300/depots/) [21310](https://steamdb.info/app/21310/depots/) [25010](https://steamdb.info/app/25010/depots/) [34400](https://steamdb.info/app/34400/depots/) [36630](https://steamdb.info/app/36630/depots/) [39300](https://steamdb.info/app/39300/depots/) [40310](https://steamdb.info/app/40310/depots/) [46250](https://steamdb.info/app/46250/depots/) [47400](https://steamdb.info/app/47400/depots/) [47430](https://steamdb.info/app/47430/depots/) [57000](https://steamdb.info/app/57000/depots/) [57010](https://steamdb.info/app/57010/depots/) [57300](https://steamdb.info/app/57300/depots/) [57310](https://steamdb.info/app/57310/depots/) [60600](https://steamdb.info/app/60600/depots/) [60610](https://steamdb.info/app/60610/depots/) [65090](https://steamdb.info/app/65090/depots/) [200630](https://steamdb.info/app/200630/depots/) [201640](https://steamdb.info/app/201640/depots/) [208710](https://steamdb.info/app/208710/depots/) [214100](https://steamdb.info/app/214100/depots/) [219990](https://steamdb.info/app/219990/depots/) [223710](https://steamdb.info/app/223710/depots/) [227940](https://steamdb.info/app/227940/depots/) [229690](https://steamdb.info/app/229690/depots/) [232890](https://steamdb.info/app/232890/depots/) [233860](https://steamdb.info/app/233860/depots/) [234980](https://steamdb.info/app/234980/depots/) [239200](https://steamdb.info/app/239200/depots/) [251690](https://steamdb.info/app/251690/depots/) [251810](https://steamdb.info/app/251810/depots/) [262390](https://steamdb.info/app/262390/depots/) [266430](https://steamdb.info/app/266430/depots/) [268890](https://steamdb.info/app/268890/depots/) [269430](https://steamdb.info/app/269430/depots/) [275670](https://steamdb.info/app/275670/depots/) [281560](https://steamdb.info/app/281560/depots/) [282140](https://steamdb.info/app/282140/depots/) [283100](https://steamdb.info/app/283100/depots/) [289950](https://steamdb.info/app/289950/depots/) [301170](https://steamdb.info/app/301170/depots/) [306490](https://steamdb.info/app/306490/depots/) [311040](https://steamdb.info/app/311040/depots/) [311120](https://steamdb.info/app/311120/depots/) [316370](https://steamdb.info/app/316370/depots/) [317970](https://steamdb.info/app/317970/depots/) [319250](https://steamdb.info/app/319250/depots/) [321900](https://steamdb.info/app/321900/depots/) [323850](https://steamdb.info/app/323850/depots/) [324460](https://steamdb.info/app/324460/depots/) [325370](https://steamdb.info/app/325370/depots/) [327030](https://steamdb.info/app/327030/depots/) [328670](https://steamdb.info/app/328670/depots/) [334310](https://steamdb.info/app/334310/depots/) [335050](https://steamdb.info/app/335050/depots/) [336210](https://steamdb.info/app/336210/depots/) [338590](https://steamdb.info/app/338590/depots/) [341960](https://steamdb.info/app/341960/depots/) [343310](https://steamdb.info/app/343310/depots/) [346630](https://steamdb.info/app/346630/depots/) [353980](https://steamdb.info/app/353980/depots/) [354280](https://steamdb.info/app/354280/depots/) [354290](https://steamdb.info/app/354290/depots/) [356580](https://steamdb.info/app/356580/depots/) [358830](https://steamdb.info/app/358830/depots/) [361830](https://steamdb.info/app/361830/depots/) [365500](https://steamdb.info/app/365500/depots/) [368670](https://steamdb.info/app/368670/depots/) [376990](https://steamdb.info/app/376990/depots/) [377040](https://steamdb.info/app/377040/depots/) [377050](https://steamdb.info/app/377050/depots/) [387770](https://steamdb.info/app/387770/depots/) [387780](https://steamdb.info/app/387780/depots/) [387790](https://steamdb.info/app/387790/depots/) [387800](https://steamdb.info/app/387800/depots/) [387810](https://steamdb.info/app/387810/depots/) [389330](https://steamdb.info/app/389330/depots/) [393340](https://steamdb.info/app/393340/depots/) [400790](https://steamdb.info/app/400790/depots/) [403200](https://steamdb.info/app/403200/depots/) [404680](https://steamdb.info/app/404680/depots/) [406030](https://steamdb.info/app/406030/depots/) [406040](https://steamdb.info/app/406040/depots/) [406050](https://steamdb.info/app/406050/depots/) [406060](https://steamdb.info/app/406060/depots/) [406830](https://steamdb.info/app/406830/depots/) [406840](https://steamdb.info/app/406840/depots/) [410900](https://steamdb.info/app/410900/depots/) [418290](https://steamdb.info/app/418290/depots/) [438020](https://steamdb.info/app/438020/depots/) [439350](https://steamdb.info/app/439350/depots/) [443070](https://steamdb.info/app/443070/depots/) [448630](https://steamdb.info/app/448630/depots/) [467520](https://steamdb.info/app/467520/depots/) [473520](https://steamdb.info/app/473520/depots/) [475150](https://steamdb.info/app/475150/depots/) [504650](https://steamdb.info/app/504650/depots/) [525080](https://steamdb.info/app/525080/depots/) [534370](https://steamdb.info/app/534370/depots/) [539440](https://steamdb.info/app/539440/depots/) [548390](https://steamdb.info/app/548390/depots/) [550900](https://steamdb.info/app/550900/depots/) [562340](https://steamdb.info/app/562340/depots/) [597840](https://steamdb.info/app/597840/depots/) [598180](https://steamdb.info/app/598180/depots/) [620170](https://steamdb.info/app/620170/depots/) [623590](https://steamdb.info/app/623590/depots/) [630280](https://steamdb.info/app/630280/depots/) [635260](https://steamdb.info/app/635260/depots/) [638610](https://steamdb.info/app/638610/depots/) [639370](https://steamdb.info/app/639370/depots/) [662170](https://steamdb.info/app/662170/depots/) [667330](https://steamdb.info/app/667330/depots/) [673560](https://steamdb.info/app/673560/depots/) [673990](https://steamdb.info/app/673990/depots/) [720060](https://steamdb.info/app/720060/depots/) [773790](https://steamdb.info/app/773790/depots/) [786040](https://steamdb.info/app/786040/depots/) [797520](https://steamdb.info/app/797520/depots/) [802190](https://steamdb.info/app/802190/depots/) [803270](https://steamdb.info/app/803270/depots/) [803290](https://steamdb.info/app/803290/depots/) [810260](https://steamdb.info/app/810260/depots/) [816590](https://steamdb.info/app/816590/depots/) [862390](https://steamdb.info/app/862390/depots/) [866740](https://steamdb.info/app/866740/depots/) [872360](https://steamdb.info/app/872360/depots/) [879660](https://steamdb.info/app/879660/depots/) [907650](https://steamdb.info/app/907650/depots/) [909870](https://steamdb.info/app/909870/depots/) [976330](https://steamdb.info/app/976330/depots/) [999220](https://steamdb.info/app/999220/depots/) [1025820](https://steamdb.info/app/1025820/depots/) [1029630](https://steamdb.info/app/1029630/depots/) [1074900](https://steamdb.info/app/1074900/depots/) [1074910](https://steamdb.info/app/1074910/depots/) [1074920](https://steamdb.info/app/1074920/depots/) [1074930](https://steamdb.info/app/1074930/depots/) [1075850](https://steamdb.info/app/1075850/depots/) [1075860](https://steamdb.info/app/1075860/depots/) [1165780](https://steamdb.info/app/1165780/depots/) [1204230](https://steamdb.info/app/1204230/depots/) [1231830](https://steamdb.info/app/1231830/depots/) [1232210](https://steamdb.info/app/1232210/depots/) [1248060](https://steamdb.info/app/1248060/depots/) [1287000](https://steamdb.info/app/1287000/depots/) [1295970](https://steamdb.info/app/1295970/depots/) [1342630](https://steamdb.info/app/1342630/depots/) [1379930](https://steamdb.info/app/1379930/depots/) [1422050](https://steamdb.info/app/1422050/depots/) [1463500](https://steamdb.info/app/1463500/depots/) [1476690](https://steamdb.info/app/1476690/depots/) [1498880](https://steamdb.info/app/1498880/depots/) [1541790](https://steamdb.info/app/1541790/depots/) [1584740](https://steamdb.info/app/1584740/depots/) [1599340](https://steamdb.info/app/1599340/depots/) [1630280](https://steamdb.info/app/1630280/depots/) [1663880](https://steamdb.info/app/1663880/depots/) [1683320](https://steamdb.info/app/1683320/depots/) [1694700](https://steamdb.info/app/1694700/depots/) [1730910](https://steamdb.info/app/1730910/depots/) [1761860](https://steamdb.info/app/1761860/depots/) [1793660](https://steamdb.info/app/1793660/depots/) [1823600](https://steamdb.info/app/1823600/depots/) [1873180](https://steamdb.info/app/1873180/depots/) [1882730](https://steamdb.info/app/1882730/depots/) [1944430](https://steamdb.info/app/1944430/depots/) [2088180](https://steamdb.info/app/2088180/depots/) [2116710](https://steamdb.info/app/2116710/depots/) [2283480](https://steamdb.info/app/2283480/depots/) [2312010](https://steamdb.info/app/2312010/depots/) [2340400](https://steamdb.info/app/2340400/depots/) [2392520](https://steamdb.info/app/2392520/depots/) [2547760](https://steamdb.info/app/2547760/depots/) [2778980](https://steamdb.info/app/2778980/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
This library is too generic

**Pull request closed without merging**
