### PR TITLE
Add rules for AMD FSR2

### PR DESCRIPTION
**Pull request by SaltyBet**
### SteamDB app page links to a few games using this

[Marvel’s Spider-Man Remastered](https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/)

### Brief explanation of the change

Add rules for AMD FidelityFX Super Resolution 2 (FSR2).

### CODE REVIEW

**Comment by xPaw** [comment]
Is spiderman the only game using this dll? I'm sure there are other games using FSR but do they have a different dll name?

**Comment by SaltyBet** [comment]
> Is spiderman the only game using this dll?

Hey, thanks for replying.

Yeah, there are more games with FSR2, but since devs can choose to [either generate the DLL or not when building the solution](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/tree/master/build), I'm guessing the file rule will only detect the presence of FSR2 if the DLL is available.

> I'm sure there are other games using FSR but do they have a different dll name?

From what I've seen, the default base DLL name pattern seems to be:

[ffx_fsr2_api_${FSR2_PLATFORM_NAME}](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/blob/master/src/ffx-fsr2-api/CMakeLists.txt)

... and it appears the base DLL will always be generated.

Depending on the rendering technology being used (Vulkan or DX12), either one of these will also be generated:

[ffx_fsr2_api_vk_${FSR2_PLATFORM_NAME}](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/blob/master/src/ffx-fsr2-api/vk/CMakeLists.txt)

[ffx_fsr2_api_dx12_${FSR2_PLATFORM_NAME}](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/blob/master/src/ffx-fsr2-api/dx12/CMakeLists.txt)

Let me know if this information is useful.

**Comment by xPaw** [comment]
I've searched for fsr2 and found just Spiderman, so yeah that's not particularly useful.

**Comment by SaltyBet** [comment]
> I've searched for fsr2 and found just Spiderman, so yeah that's not particularly useful.

Quick update, [Red Dead Redemption 2 has officially implemented FSR](https://steamdb.info/patchnotes/9446894/).

They're using the DLLs:

RDR 2 FSR 2 info

**Pull request merged**
