### PR TITLE
Update Tyrano

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/1688400/
https://steamdb.info/app/1737150/

### Brief explanation of the change
The only way to identify these is a save file.

### CODE REVIEW

**Review by Lifeismana — DISMISSED** [review]
Missing description and some non matching strings

**Comment by MichaelHinrichs** [comment]
Tyrano Builder already has a description.

**Comment by MichaelHinrichs** [comment]
Done, I guess.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.TyranoBuilder**

These apps now match: **(167)** [345370](https://steamdb.info/app/345370/depots/) [379980](https://steamdb.info/app/379980/depots/) [407680](https://steamdb.info/app/407680/depots/) [416630](https://steamdb.info/app/416630/depots/) [436300](https://steamdb.info/app/436300/depots/) [459130](https://steamdb.info/app/459130/depots/) [460150](https://steamdb.info/app/460150/depots/) [471260](https://steamdb.info/app/471260/depots/) [485800](https://steamdb.info/app/485800/depots/) [492280](https://steamdb.info/app/492280/depots/) [544190](https://steamdb.info/app/544190/depots/) [546490](https://steamdb.info/app/546490/depots/) [551520](https://steamdb.info/app/551520/depots/) [557880](https://steamdb.info/app/557880/depots/) [587570](https://steamdb.info/app/587570/depots/) [601570](https://steamdb.info/app/601570/depots/) [632290](https://steamdb.info/app/632290/depots/) [657900](https://steamdb.info/app/657900/depots/) [664420](https://steamdb.info/app/664420/depots/) [664570](https://steamdb.info/app/664570/depots/) [678190](https://steamdb.info/app/678190/depots/) [682150](https://steamdb.info/app/682150/depots/) [688260](https://steamdb.info/app/688260/depots/) [722760](https://steamdb.info/app/722760/depots/) [765400](https://steamdb.info/app/765400/depots/) [774451](https://steamdb.info/app/774451/depots/) [778760](https://steamdb.info/app/778760/depots/) [788740](https://steamdb.info/app/788740/depots/) [794410](https://steamdb.info/app/794410/depots/) [836940](https://steamdb.info/app/836940/depots/) [843330](https://steamdb.info/app/843330/depots/) [852630](https://steamdb.info/app/852630/depots/) [883390](https://steamdb.info/app/883390/depots/) [888260](https://steamdb.info/app/888260/depots/) [889030](https://steamdb.info/app/889030/depots/) [891870](https://steamdb.info/app/891870/depots/) [896190](https://steamdb.info/app/896190/depots/) [906590](https://steamdb.info/app/906590/depots/) [929640](https://steamdb.info/app/929640/depots/) [931870](https://steamdb.info/app/931870/depots/) [931900](https://steamdb.info/app/931900/depots/) [932070](https://steamdb.info/app/932070/depots/) [936150](https://steamdb.info/app/936150/depots/) [940250](https://steamdb.info/app/940250/depots/) [942370](https://steamdb.info/app/942370/depots/) [943860](https://steamdb.info/app/943860/depots/) [957410](https://steamdb.info/app/957410/depots/) [979220](https://steamdb.info/app/979220/depots/) [979680](https://steamdb.info/app/979680/depots/) [985330](https://steamdb.info/app/985330/depots/) [1016750](https://steamdb.info/app/1016750/depots/) [1017940](https://steamdb.info/app/1017940/depots/) [1018380](https://steamdb.info/app/1018380/depots/) [1018930](https://steamdb.info/app/1018930/depots/) [1025080](https://steamdb.info/app/1025080/depots/) [1047670](https://steamdb.info/app/1047670/depots/) [1048090](https://steamdb.info/app/1048090/depots/) [1072950](https://steamdb.info/app/1072950/depots/) [1090470](https://steamdb.info/app/1090470/depots/) [1097830](https://steamdb.info/app/1097830/depots/) [1117770](https://steamdb.info/app/1117770/depots/) [1127070](https://steamdb.info/app/1127070/depots/) [1143460](https://steamdb.info/app/1143460/depots/) [1148260](https://steamdb.info/app/1148260/depots/) [1154440](https://steamdb.info/app/1154440/depots/) [1179350](https://steamdb.info/app/1179350/depots/) [1182450](https://steamdb.info/app/1182450/depots/) [1198320](https://steamdb.info/app/1198320/depots/) [1216080](https://steamdb.info/app/1216080/depots/) [1216130](https://steamdb.info/app/1216130/depots/) [1232380](https://steamdb.info/app/1232380/depots/) [1236480](https://steamdb.info/app/1236480/depots/) [1249850](https://steamdb.info/app/1249850/depots/) [1284300](https://steamdb.info/app/1284300/depots/) [1285850](https://steamdb.info/app/1285850/depots/) [1304140](https://steamdb.info/app/1304140/depots/) [1322260](https://steamdb.info/app/1322260/depots/) [1338670](https://steamdb.info/app/1338670/depots/) [1351810](https://steamdb.info/app/1351810/depots/) [1361260](https://steamdb.info/app/1361260/depots/) [1368860](https://steamdb.info/app/1368860/depots/) [1371880](https://steamdb.info/app/1371880/depots/) [1377400](https://steamdb.info/app/1377400/depots/) [1382840](https://steamdb.info/app/1382840/depots/) [1390900](https://steamdb.info/app/1390900/depots/) [1394080](https://steamdb.info/app/1394080/depots/) [1403010](https://steamdb.info/app/1403010/depots/) [1403180](https://steamdb.info/app/1403180/depots/) [1418090](https://steamdb.info/app/1418090/depots/) [1432490](https://steamdb.info/app/1432490/depots/) [1444360](https://steamdb.info/app/1444360/depots/) [1447190](https://steamdb.info/app/1447190/depots/) [1450680](https://steamdb.info/app/1450680/depots/) [1471940](https://steamdb.info/app/1471940/depots/) [1478410](https://steamdb.info/app/1478410/depots/) [1521670](https://steamdb.info/app/1521670/depots/) [1530140](https://steamdb.info/app/1530140/depots/) [1547930](https://steamdb.info/app/1547930/depots/) [1573120](https://steamdb.info/app/1573120/depots/) [1579640](https://steamdb.info/app/1579640/depots/) [1592970](https://steamdb.info/app/1592970/depots/) [1636260](https://steamdb.info/app/1636260/depots/) [1680260](https://steamdb.info/app/1680260/depots/) [1688400](https://steamdb.info/app/1688400/depots/) [1697780](https://steamdb.info/app/1697780/depots/) [1708130](https://steamdb.info/app/1708130/depots/) [1737150](https://steamdb.info/app/1737150/depots/) [1746530](https://steamdb.info/app/1746530/depots/) [1748240](https://steamdb.info/app/1748240/depots/) [1757420](https://steamdb.info/app/1757420/depots/) [1775920](https://steamdb.info/app/1775920/depots/) [1807600](https://steamdb.info/app/1807600/depots/) [1811290](https://steamdb.info/app/1811290/depots/) [1869370](https://steamdb.info/app/1869370/depots/) [1873000](https://steamdb.info/app/1873000/depots/) [1882670](https://steamdb.info/app/1882670/depots/) [1897720](https://steamdb.info/app/1897720/depots/) [1938040](https://steamdb.info/app/1938040/depots/) [1945000](https://steamdb.info/app/1945000/depots/) [1950310](https://steamdb.info/app/1950310/depots/) [1951300](https://steamdb.info/app/1951300/depots/) [1957470](https://steamdb.info/app/1957470/depots/) [1985310](https://steamdb.info/app/1985310/depots/) [2053760](https://steamdb.info/app/2053760/depots/) [2061140](https://steamdb.info/app/2061140/depots/) [2071810](https://steamdb.info/app/2071810/depots/) [2095840](https://steamdb.info/app/2095840/depots/) [2101130](https://steamdb.info/app/2101130/depots/) [2124520](https://steamdb.info/app/2124520/depots/) [2128680](https://steamdb.info/app/2128680/depots/) [2148610](https://steamdb.info/app/2148610/depots/) [2149660](https://steamdb.info/app/2149660/depots/) [2154800](https://steamdb.info/app/2154800/depots/) [2156880](https://steamdb.info/app/2156880/depots/) [2165550](https://steamdb.info/app/2165550/depots/) [2168610](https://steamdb.info/app/2168610/depots/) [2168660](https://steamdb.info/app/2168660/depots/) [2181290](https://steamdb.info/app/2181290/depots/) [2181990](https://steamdb.info/app/2181990/depots/) [2201190](https://steamdb.info/app/2201190/depots/) [2235390](https://steamdb.info/app/2235390/depots/) [2236660](https://steamdb.info/app/2236660/depots/) [2240600](https://steamdb.info/app/2240600/depots/) [2278380](https://steamdb.info/app/2278380/depots/) [2283120](https://steamdb.info/app/2283120/depots/) [2288840](https://steamdb.info/app/2288840/depots/) [2294930](https://steamdb.info/app/2294930/depots/) [2305910](https://steamdb.info/app/2305910/depots/) [2311330](https://steamdb.info/app/2311330/depots/) [2322690](https://steamdb.info/app/2322690/depots/) [2344040](https://steamdb.info/app/2344040/depots/) [2348740](https://steamdb.info/app/2348740/depots/) [2365480](https://steamdb.info/app/2365480/depots/) [2423320](https://steamdb.info/app/2423320/depots/) [2439580](https://steamdb.info/app/2439580/depots/) [2460000](https://steamdb.info/app/2460000/depots/) [2498300](https://steamdb.info/app/2498300/depots/) [2500110](https://steamdb.info/app/2500110/depots/) [2597520](https://steamdb.info/app/2597520/depots/) [2623730](https://steamdb.info/app/2623730/depots/) [2661180](https://steamdb.info/app/2661180/depots/) [2725430](https://steamdb.info/app/2725430/depots/) [2745790](https://steamdb.info/app/2745790/depots/) [2757490](https://steamdb.info/app/2757490/depots/) [2792680](https://steamdb.info/app/2792680/depots/) [2829210](https://steamdb.info/app/2829210/depots/) [2865850](https://steamdb.info/app/2865850/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
merged in 901ae13067bc1ba78278477322f6febd9c5784bd

**Pull request closed without merging**
