### PR TITLE
Add NVIDIA APEX

### PR DESCRIPTION
**Pull request by Lifeismana**
### SteamDB app page links to a few games using this
https://steamdb.info/app/49520/
https://steamdb.info/app/232090/
https://steamdb.info/app/208650/
https://steamdb.info/app/209160/
### Brief explanation of the change
Add Nvidia Apex as an sdk

I'm not a big fan of that regex since it's so big but simply looking for apex would bring some false positive and the list of games that uses it is so big that i don't have the willingness to find out if the "framework" one is never used without one of the other one

### CODE REVIEW

**Comment by xPaw** [comment]
https://gameworksdocs.nvidia.com/APEX/1.4/docs/APEX_Framework/APEX_PG_Deployment.html

Are you sure framework isn't always present?

**Comment by Lifeismana** [comment]
yeah, one such exemple is Batman: Arkham Asylum https://steamdb.info/app/35010/depots/
it uses apex_release.dll

**Comment by xPaw** [comment]
Any others? I'd rather not list every variant in regex.

**Comment by Lifeismana** [comment]
yeah agree with you, most likely we can reduce it to `(?:^|/)apex(?:framework|_framework|_loader|_release)`
loader is needed for project Cars (`_legacy` could also work but makes less sense with the rest) 
https://steamdb.info/app/234630/depots/

**Pull request merged**
