### PR TITLE
Add Debug Help Library

### LINKED ISSUE #300: Add DbgHelp detection
### Some reference to the SDK, such as the developer site or a wikipedia article.

DbgHelp  https://learn.microsoft.com/en-us/windows/win32/debug/dbghelp-versions

### SteamDB links

https://steamdb.info/app/230410
https://steamdb.info/app/570/

### Possible way to detect it

Contain any of the file: dbghelp.dll

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

https://steamdb.info/app/230410
https://steamdb.info/app/570/

### Brief explanation of the change

closes #300 
Added a rule for DbgHelp

### CODE REVIEW

**Comment by xPaw** [comment]
This appears to come by default with Unreal engine, which makes it not that useful.

**Comment by LinXP** [comment]
> This appears to come by default with Unreal engine, which makes it not that useful.

No, there are many other uses
https://steamdb.info/depot/529491/
https://steamdb.info/app/570/depots/

**Comment by diedyesterdaywashere** [comment]
but yeah, it's not only found in unreal games, so it wouldnt hurt to track it i guess

**Comment by diedyesterdaywashere** [comment]
regex is pretty cheap(i think?) too, it just looks for one keyword, and does not have any other variants

**Pull request closed without merging**
