### PR TITLE
Loom

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/710700/

### Brief explanation of the change
Detect Loom SDK by it's ".loom" file type.

### CODE REVIEW

**Comment by Lifeismana** [comment]
missing non matching tests

**Comment by MichaelHinrichs** [comment]
Done.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.Loom**

These apps now match: **(1)** [710700](https://steamdb.info/app/710700/depots/)

Please confirm that all these changed apps are correct.

**Comment by MichaelHinrichs** [comment]
Only applies to one app.

**Pull request closed without merging**
