### PR TITLE
Add Cobra Engine

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
 - [Planet Coaster](https://steamdb.info/app/493340)
 - [Planet Zoo](https://steamdb.info/app/703080)
 - [Disneyland Adventures](https://steamdb.info/app/630610)
 - [RollerCoaster Tycoon® 3: Complete Edition](https://steamdb.info/app/1368820)
 - [Jurassic World Evolution](https://steamdb.info/app/648350)
 - [Elite Dangerous](https://steamdb.info/app/359320)
 - [Zoo Tycoon](https://steamdb.info/app/613880)

### Brief explanation of the change
Find Cobra from it's ovl file type.

### CODE REVIEW

**Comment by MichaelHinrichs** [comment]
`Path "DFDFAGIDATA.OVL" returned "Engine.Cobra" but it should not have matched anything`
Ok, who put that there?

**Comment by xPaw** [comment]
There's this rule:
https://github.com/SteamDatabase/FileDetectionRuleSets/blob/f3b1fc368c21033fa94180e89994cefbf86d5bd8/rules.ini#L38

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.Cobra**

These apps now match: **(104)** [2700](https://steamdb.info/app/2700/depots/) [7660](https://steamdb.info/app/7660/depots/) [10100](https://steamdb.info/app/10100/depots/) [10110](https://steamdb.info/app/10110/depots/) [224960](https://steamdb.info/app/224960/depots/) [240160](https://steamdb.info/app/240160/depots/) [240180](https://steamdb.info/app/240180/depots/) [245410](https://steamdb.info/app/245410/depots/) [245430](https://steamdb.info/app/245430/depots/) [263940](https://steamdb.info/app/263940/depots/) [267670](https://steamdb.info/app/267670/depots/) [282010](https://steamdb.info/app/282010/depots/) [287020](https://steamdb.info/app/287020/depots/) [308000](https://steamdb.info/app/308000/depots/) [327380](https://steamdb.info/app/327380/depots/) [327390](https://steamdb.info/app/327390/depots/) [327400](https://steamdb.info/app/327400/depots/) [327920](https://steamdb.info/app/327920/depots/) [327930](https://steamdb.info/app/327930/depots/) [327940](https://steamdb.info/app/327940/depots/) [327950](https://steamdb.info/app/327950/depots/) [328430](https://steamdb.info/app/328430/depots/) [328920](https://steamdb.info/app/328920/depots/) [328930](https://steamdb.info/app/328930/depots/) [329620](https://steamdb.info/app/329620/depots/) [329630](https://steamdb.info/app/329630/depots/) [329640](https://steamdb.info/app/329640/depots/) [329650](https://steamdb.info/app/329650/depots/) [329660](https://steamdb.info/app/329660/depots/) [329670](https://steamdb.info/app/329670/depots/) [329680](https://steamdb.info/app/329680/depots/) [347230](https://steamdb.info/app/347230/depots/) [347240](https://steamdb.info/app/347240/depots/) [347250](https://steamdb.info/app/347250/depots/) [347260](https://steamdb.info/app/347260/depots/) [347270](https://steamdb.info/app/347270/depots/) [351810](https://steamdb.info/app/351810/depots/) [351820](https://steamdb.info/app/351820/depots/) [354430](https://steamdb.info/app/354430/depots/) [355250](https://steamdb.info/app/355250/depots/) [358170](https://steamdb.info/app/358170/depots/) [358180](https://steamdb.info/app/358180/depots/) [358190](https://steamdb.info/app/358190/depots/) [358200](https://steamdb.info/app/358200/depots/) [358210](https://steamdb.info/app/358210/depots/) [358220](https://steamdb.info/app/358220/depots/) [358230](https://steamdb.info/app/358230/depots/) [358240](https://steamdb.info/app/358240/depots/) [358250](https://steamdb.info/app/358250/depots/) [358280](https://steamdb.info/app/358280/depots/) [358290](https://steamdb.info/app/358290/depots/) [358300](https://steamdb.info/app/358300/depots/) [358310](https://steamdb.info/app/358310/depots/) [358320](https://steamdb.info/app/358320/depots/) [358330](https://steamdb.info/app/358330/depots/) [358340](https://steamdb.info/app/358340/depots/) [358360](https://steamdb.info/app/358360/depots/) [358370](https://steamdb.info/app/358370/depots/) [358380](https://steamdb.info/app/358380/depots/) [358400](https://steamdb.info/app/358400/depots/) [358410](https://steamdb.info/app/358410/depots/) [358420](https://steamdb.info/app/358420/depots/) [358440](https://steamdb.info/app/358440/depots/) [358920](https://steamdb.info/app/358920/depots/) [359320](https://steamdb.info/app/359320/depots/) [359850](https://steamdb.info/app/359850/depots/) [368600](https://steamdb.info/app/368600/depots/) [376750](https://steamdb.info/app/376750/depots/) [410540](https://steamdb.info/app/410540/depots/) [410550](https://steamdb.info/app/410550/depots/) [410700](https://steamdb.info/app/410700/depots/) [419270](https://steamdb.info/app/419270/depots/) [447780](https://steamdb.info/app/447780/depots/) [447800](https://steamdb.info/app/447800/depots/) [464360](https://steamdb.info/app/464360/depots/) [493340](https://steamdb.info/app/493340/depots/) [494740](https://steamdb.info/app/494740/depots/) [510590](https://steamdb.info/app/510590/depots/) [518340](https://steamdb.info/app/518340/depots/) [559640](https://steamdb.info/app/559640/depots/) [569200](https://steamdb.info/app/569200/depots/) [573790](https://steamdb.info/app/573790/depots/) [613880](https://steamdb.info/app/613880/depots/) [630610](https://steamdb.info/app/630610/depots/) [648350](https://steamdb.info/app/648350/depots/) [690250](https://steamdb.info/app/690250/depots/) [698620](https://steamdb.info/app/698620/depots/) [703080](https://steamdb.info/app/703080/depots/) [763970](https://steamdb.info/app/763970/depots/) [1006450](https://steamdb.info/app/1006450/depots/) [1028460](https://steamdb.info/app/1028460/depots/) [1244460](https://steamdb.info/app/1244460/depots/) [1244830](https://steamdb.info/app/1244830/depots/) [1297560](https://steamdb.info/app/1297560/depots/) [1357570](https://steamdb.info/app/1357570/depots/) [1368630](https://steamdb.info/app/1368630/depots/) [1368820](https://steamdb.info/app/1368820/depots/) [1844380](https://steamdb.info/app/1844380/depots/) [2061230](https://steamdb.info/app/2061230/depots/) [2109710](https://steamdb.info/app/2109710/depots/) [2386290](https://steamdb.info/app/2386290/depots/) [2597890](https://steamdb.info/app/2597890/depots/) [2702100](https://steamdb.info/app/2702100/depots/) [2766050](https://steamdb.info/app/2766050/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
merged in a927237e803e6752861eb40643eb059c47cf89c6

**Pull request closed without merging**
