### PR TITLE
Add Tiled Map Editor SDK

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
 - [Don't Starve](https://steamdb.info/app/219740)
 - [Titan Souls](https://steamdb.info/app/297130)
 - [Don't Starve Together](https://steamdb.info/app/322330)
 - [Inexistence](https://steamdb.info/app/444720)
 - [Bubblegum Bandit](https://steamdb.info/app/2460680)
 - [Clicks Of Courage](https://steamdb.info/app/2379650)
 - [建安外史 The Tales of Jian An](https://steamdb.info/app/1973610)
 - [Sentinel 3: Homeworld](https://steamdb.info/app/275350)
 - [PowerUp Elevation](https://steamdb.info/app/879390/)
 - [Curse of the Great Forest](https://steamdb.info/app/652060)
 - [Rouge Tank](https://steamdb.info/app/2889870)
 - [Defender's Quest: Valley of the Forgotten](https://steamdb.info/app/218410)
 - [Defender's Quest 2: Mists of Ruin](https://steamdb.info/app/252190)
 - [Holobunnies: Pause Cafe](https://steamdb.info/app/497710)

### Brief explanation of the change
Find TMX files from Tiled Map Editor.

### CODE REVIEW

**Comment by Faalagorn** [comment]
Just noting that Project Zomboid https://steamdb.info/app/108600/ uses tiled, and updated tiled editor is downloadable via https://steamdb.info/app/380880/ as well.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.Tiled\_Map\_Editor**

These apps now match: **(275)** [17400](https://steamdb.info/app/17400/depots/) [17430](https://steamdb.info/app/17430/depots/) [24850](https://steamdb.info/app/24850/depots/) [47850](https://steamdb.info/app/47850/depots/) [95400](https://steamdb.info/app/95400/depots/) [218410](https://steamdb.info/app/218410/depots/) [219740](https://steamdb.info/app/219740/depots/) [223090](https://steamdb.info/app/223090/depots/) [227720](https://steamdb.info/app/227720/depots/) [229690](https://steamdb.info/app/229690/depots/) [235250](https://steamdb.info/app/235250/depots/) [245850](https://steamdb.info/app/245850/depots/) [252190](https://steamdb.info/app/252190/depots/) [265470](https://steamdb.info/app/265470/depots/) [270050](https://steamdb.info/app/270050/depots/) [271140](https://steamdb.info/app/271140/depots/) [275350](https://steamdb.info/app/275350/depots/) [275470](https://steamdb.info/app/275470/depots/) [280360](https://steamdb.info/app/280360/depots/) [288020](https://steamdb.info/app/288020/depots/) [289130](https://steamdb.info/app/289130/depots/) [291190](https://steamdb.info/app/291190/depots/) [292400](https://steamdb.info/app/292400/depots/) [297130](https://steamdb.info/app/297130/depots/) [304520](https://steamdb.info/app/304520/depots/) [313080](https://steamdb.info/app/313080/depots/) [322110](https://steamdb.info/app/322110/depots/) [325150](https://steamdb.info/app/325150/depots/) [328510](https://steamdb.info/app/328510/depots/) [331190](https://steamdb.info/app/331190/depots/) [332360](https://steamdb.info/app/332360/depots/) [332760](https://steamdb.info/app/332760/depots/) [333210](https://steamdb.info/app/333210/depots/) [334270](https://steamdb.info/app/334270/depots/) [335620](https://steamdb.info/app/335620/depots/) [346420](https://steamdb.info/app/346420/depots/) [346970](https://steamdb.info/app/346970/depots/) [356070](https://steamdb.info/app/356070/depots/) [358830](https://steamdb.info/app/358830/depots/) [359950](https://steamdb.info/app/359950/depots/) [363550](https://steamdb.info/app/363550/depots/) [365120](https://steamdb.info/app/365120/depots/) [365480](https://steamdb.info/app/365480/depots/) [370020](https://steamdb.info/app/370020/depots/) [370390](https://steamdb.info/app/370390/depots/) [372250](https://steamdb.info/app/372250/depots/) [375290](https://steamdb.info/app/375290/depots/) [379640](https://steamdb.info/app/379640/depots/) [380880](https://steamdb.info/app/380880/depots/) [383020](https://steamdb.info/app/383020/depots/) [383720](https://steamdb.info/app/383720/depots/) [386840](https://steamdb.info/app/386840/depots/) [396350](https://steamdb.info/app/396350/depots/) [398900](https://steamdb.info/app/398900/depots/) [404350](https://steamdb.info/app/404350/depots/) [405810](https://steamdb.info/app/405810/depots/) [416310](https://steamdb.info/app/416310/depots/) [429690](https://steamdb.info/app/429690/depots/) [433210](https://steamdb.info/app/433210/depots/) [433600](https://steamdb.info/app/433600/depots/) [437890](https://steamdb.info/app/437890/depots/) [444720](https://steamdb.info/app/444720/depots/) [449310](https://steamdb.info/app/449310/depots/) [450700](https://steamdb.info/app/450700/depots/) [456130](https://steamdb.info/app/456130/depots/) [459830](https://steamdb.info/app/459830/depots/) [461860](https://steamdb.info/app/461860/depots/) [462620](https://steamdb.info/app/462620/depots/) [473790](https://steamdb.info/app/473790/depots/) [485640](https://steamdb.info/app/485640/depots/) [485660](https://steamdb.info/app/485660/depots/) [485750](https://steamdb.info/app/485750/depots/) [497710](https://steamdb.info/app/497710/depots/) [524860](https://steamdb.info/app/524860/depots/) [525380](https://steamdb.info/app/525380/depots/) [525740](https://steamdb.info/app/525740/depots/) [534240](https://steamdb.info/app/534240/depots/) [562330](https://steamdb.info/app/562330/depots/) [577380](https://steamdb.info/app/577380/depots/) [581910](https://steamdb.info/app/581910/depots/) [591640](https://steamdb.info/app/591640/depots/) [621000](https://steamdb.info/app/621000/depots/) [622440](https://steamdb.info/app/622440/depots/) [623770](https://steamdb.info/app/623770/depots/) [630720](https://steamdb.info/app/630720/depots/) [643830](https://steamdb.info/app/643830/depots/) [647960](https://steamdb.info/app/647960/depots/) [652060](https://steamdb.info/app/652060/depots/) [655350](https://steamdb.info/app/655350/depots/) [655380](https://steamdb.info/app/655380/depots/) [656510](https://steamdb.info/app/656510/depots/) [661270](https://steamdb.info/app/661270/depots/) [664240](https://steamdb.info/app/664240/depots/) [666870](https://steamdb.info/app/666870/depots/) [670160](https://steamdb.info/app/670160/depots/) [681460](https://steamdb.info/app/681460/depots/) [690560](https://steamdb.info/app/690560/depots/) [695650](https://steamdb.info/app/695650/depots/) [703090](https://steamdb.info/app/703090/depots/) [705410](https://steamdb.info/app/705410/depots/) [711810](https://steamdb.info/app/711810/depots/) [722660](https://steamdb.info/app/722660/depots/) [724300](https://steamdb.info/app/724300/depots/) [725040](https://steamdb.info/app/725040/depots/) [725660](https://steamdb.info/app/725660/depots/) [731420](https://steamdb.info/app/731420/depots/) [747110](https://steamdb.info/app/747110/depots/) [758870](https://steamdb.info/app/758870/depots/) [758880](https://steamdb.info/app/758880/depots/) [770050](https://steamdb.info/app/770050/depots/) [770200](https://steamdb.info/app/770200/depots/) [770340](https://steamdb.info/app/770340/depots/) [779670](https://steamdb.info/app/779670/depots/) [787810](https://steamdb.info/app/787810/depots/) [792200](https://steamdb.info/app/792200/depots/) [793620](https://steamdb.info/app/793620/depots/) [795180](https://steamdb.info/app/795180/depots/) [797710](https://steamdb.info/app/797710/depots/) [808130](https://steamdb.info/app/808130/depots/) [813650](https://steamdb.info/app/813650/depots/) [818480](https://steamdb.info/app/818480/depots/) [822640](https://steamdb.info/app/822640/depots/) [829420](https://steamdb.info/app/829420/depots/) [839510](https://steamdb.info/app/839510/depots/) [863920](https://steamdb.info/app/863920/depots/) [879390](https://steamdb.info/app/879390/depots/) [883190](https://steamdb.info/app/883190/depots/) [921450](https://steamdb.info/app/921450/depots/) [927840](https://steamdb.info/app/927840/depots/) [953490](https://steamdb.info/app/953490/depots/) [963470](https://steamdb.info/app/963470/depots/) [963870](https://steamdb.info/app/963870/depots/) [976380](https://steamdb.info/app/976380/depots/) [994250](https://steamdb.info/app/994250/depots/) [1006680](https://steamdb.info/app/1006680/depots/) [1011530](https://steamdb.info/app/1011530/depots/) [1023990](https://steamdb.info/app/1023990/depots/) [1029210](https://steamdb.info/app/1029210/depots/) [1029970](https://steamdb.info/app/1029970/depots/) [1036600](https://steamdb.info/app/1036600/depots/) [1037140](https://steamdb.info/app/1037140/depots/) [1053390](https://steamdb.info/app/1053390/depots/) [1054630](https://steamdb.info/app/1054630/depots/) [1063210](https://steamdb.info/app/1063210/depots/) [1063540](https://steamdb.info/app/1063540/depots/) [1098930](https://steamdb.info/app/1098930/depots/) [1122930](https://steamdb.info/app/1122930/depots/) [1145180](https://steamdb.info/app/1145180/depots/) [1148320](https://steamdb.info/app/1148320/depots/) [1163560](https://steamdb.info/app/1163560/depots/) [1191940](https://steamdb.info/app/1191940/depots/) [1253130](https://steamdb.info/app/1253130/depots/) [1262500](https://steamdb.info/app/1262500/depots/) [1278190](https://steamdb.info/app/1278190/depots/) [1280300](https://steamdb.info/app/1280300/depots/) [1289010](https://steamdb.info/app/1289010/depots/) [1297390](https://steamdb.info/app/1297390/depots/) [1314740](https://steamdb.info/app/1314740/depots/) [1328080](https://steamdb.info/app/1328080/depots/) [1355760](https://steamdb.info/app/1355760/depots/) [1381540](https://steamdb.info/app/1381540/depots/) [1382490](https://steamdb.info/app/1382490/depots/) [1389370](https://steamdb.info/app/1389370/depots/) [1399700](https://steamdb.info/app/1399700/depots/) [1401640](https://steamdb.info/app/1401640/depots/) [1418650](https://steamdb.info/app/1418650/depots/) [1424010](https://steamdb.info/app/1424010/depots/) [1436590](https://steamdb.info/app/1436590/depots/) [1447420](https://steamdb.info/app/1447420/depots/) [1448070](https://steamdb.info/app/1448070/depots/) [1462590](https://steamdb.info/app/1462590/depots/) [1462630](https://steamdb.info/app/1462630/depots/) [1467360](https://steamdb.info/app/1467360/depots/) [1471100](https://steamdb.info/app/1471100/depots/) [1485730](https://steamdb.info/app/1485730/depots/) [1488330](https://steamdb.info/app/1488330/depots/) [1493700](https://steamdb.info/app/1493700/depots/) [1508960](https://steamdb.info/app/1508960/depots/) [1520090](https://steamdb.info/app/1520090/depots/) [1526520](https://steamdb.info/app/1526520/depots/) [1528830](https://steamdb.info/app/1528830/depots/) [1533150](https://steamdb.info/app/1533150/depots/) [1574760](https://steamdb.info/app/1574760/depots/) [1578810](https://steamdb.info/app/1578810/depots/) [1582810](https://steamdb.info/app/1582810/depots/) [1586330](https://steamdb.info/app/1586330/depots/) [1591440](https://steamdb.info/app/1591440/depots/) [1597720](https://steamdb.info/app/1597720/depots/) [1657540](https://steamdb.info/app/1657540/depots/) [1661130](https://steamdb.info/app/1661130/depots/) [1661600](https://steamdb.info/app/1661600/depots/) [1666620](https://steamdb.info/app/1666620/depots/) [1671170](https://steamdb.info/app/1671170/depots/) [1674050](https://steamdb.info/app/1674050/depots/) [1682060](https://steamdb.info/app/1682060/depots/) [1699320](https://steamdb.info/app/1699320/depots/) [1715490](https://steamdb.info/app/1715490/depots/) [1716350](https://steamdb.info/app/1716350/depots/) [1724060](https://steamdb.info/app/1724060/depots/) [1731270](https://steamdb.info/app/1731270/depots/) [1736060](https://steamdb.info/app/1736060/depots/) [1747830](https://steamdb.info/app/1747830/depots/) [1761410](https://steamdb.info/app/1761410/depots/) [1766490](https://steamdb.info/app/1766490/depots/) [1780850](https://steamdb.info/app/1780850/depots/) [1785430](https://steamdb.info/app/1785430/depots/) [1821310](https://steamdb.info/app/1821310/depots/) [1854280](https://steamdb.info/app/1854280/depots/) [1875240](https://steamdb.info/app/1875240/depots/) [1884010](https://steamdb.info/app/1884010/depots/) [1901730](https://steamdb.info/app/1901730/depots/) [1904670](https://steamdb.info/app/1904670/depots/) [1908170](https://steamdb.info/app/1908170/depots/) [1943160](https://steamdb.info/app/1943160/depots/) [1953110](https://steamdb.info/app/1953110/depots/) [1968500](https://steamdb.info/app/1968500/depots/) [1969660](https://steamdb.info/app/1969660/depots/) [1973610](https://steamdb.info/app/1973610/depots/) [1976850](https://steamdb.info/app/1976850/depots/) [1977920](https://steamdb.info/app/1977920/depots/) [1978240](https://steamdb.info/app/1978240/depots/) [1993240](https://steamdb.info/app/1993240/depots/) [2003510](https://steamdb.info/app/2003510/depots/) [2027620](https://steamdb.info/app/2027620/depots/) [2067700](https://steamdb.info/app/2067700/depots/) [2070320](https://steamdb.info/app/2070320/depots/) [2121050](https://steamdb.info/app/2121050/depots/) [2140120](https://steamdb.info/app/2140120/depots/) [2147900](https://steamdb.info/app/2147900/depots/) [2154840](https://steamdb.info/app/2154840/depots/) [2157410](https://steamdb.info/app/2157410/depots/) [2188930](https://steamdb.info/app/2188930/depots/) [2191820](https://steamdb.info/app/2191820/depots/) [2192840](https://steamdb.info/app/2192840/depots/) [2221070](https://steamdb.info/app/2221070/depots/) [2242510](https://steamdb.info/app/2242510/depots/) [2276480](https://steamdb.info/app/2276480/depots/) [2290550](https://steamdb.info/app/2290550/depots/) [2305880](https://steamdb.info/app/2305880/depots/) [2314960](https://steamdb.info/app/2314960/depots/) [2326590](https://steamdb.info/app/2326590/depots/) [2336660](https://steamdb.info/app/2336660/depots/) [2338630](https://steamdb.info/app/2338630/depots/) [2338690](https://steamdb.info/app/2338690/depots/) [2349820](https://steamdb.info/app/2349820/depots/) [2366000](https://steamdb.info/app/2366000/depots/) [2379650](https://steamdb.info/app/2379650/depots/) [2381160](https://steamdb.info/app/2381160/depots/) [2399360](https://steamdb.info/app/2399360/depots/) [2416770](https://steamdb.info/app/2416770/depots/) [2420440](https://steamdb.info/app/2420440/depots/) [2430830](https://steamdb.info/app/2430830/depots/) [2441260](https://steamdb.info/app/2441260/depots/) [2460680](https://steamdb.info/app/2460680/depots/) [2461400](https://steamdb.info/app/2461400/depots/) [2461410](https://steamdb.info/app/2461410/depots/) [2480740](https://steamdb.info/app/2480740/depots/) [2509860](https://steamdb.info/app/2509860/depots/) [2533970](https://steamdb.info/app/2533970/depots/) [2575360](https://steamdb.info/app/2575360/depots/) [2585100](https://steamdb.info/app/2585100/depots/) [2589280](https://steamdb.info/app/2589280/depots/) [2609520](https://steamdb.info/app/2609520/depots/) [2634720](https://steamdb.info/app/2634720/depots/) [2640520](https://steamdb.info/app/2640520/depots/) [2661230](https://steamdb.info/app/2661230/depots/) [2693730](https://steamdb.info/app/2693730/depots/) [2716190](https://steamdb.info/app/2716190/depots/) [2719440](https://steamdb.info/app/2719440/depots/) [2757780](https://steamdb.info/app/2757780/depots/) [2762060](https://steamdb.info/app/2762060/depots/) [2785390](https://steamdb.info/app/2785390/depots/) [2800070](https://steamdb.info/app/2800070/depots/) [2872650](https://steamdb.info/app/2872650/depots/) [2894110](https://steamdb.info/app/2894110/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
Putting games that aren't detect by your rule isn't the purpose of the "SteamDB app page links to a few games using this" section

**Comment by Lifeismana** [comment]
merged in https://github.com/SteamDatabase/FileDetectionRuleSets/commit/e699808b527ca4dfad39a4edf3caffa6f66a1052

**Pull request closed without merging**
