### PR TITLE
Add FlaxEngine

### PR DESCRIPTION
**Pull request by honzapatCZ**
Adds flaxengine
https://flaxengine.com/

### CODE REVIEW

**Comment by xPaw** [comment]
Please see https://github.com/SteamDatabase/FileDetectionRuleSets/blob/main/CONTRIBUTING.md#contributing

**Comment by xPaw** [comment]
There are no games on Steam that have `FlaxEngine` or `Game.Build.json` in the files.

**Comment by larsiusprime** [comment]
If there's literally no games on Steam that use this engine, then I don't think we should add the rule.

**Comment by honzapatCZ** [comment]
OK, given that its a new engine could this be converted to a draft and merged once there are some games actually?

**Comment by diedyesterdaywashere** [comment]
i wonder if there are any games on this engine now...

**Comment by Lifeismana** [comment]
not really:
https://steamdb.info/app/1627770/
https://steamdb.info/app/2138130/

**Comment by diedyesterdaywashere** [comment]
rip

**Pull request closed without merging**
