### PR TITLE
Engines/frostbite

### PR DESCRIPTION
**Pull request by Suvitruf**
### SteamDB app page links to a few games using this

https://steamdb.info/depot/1222731/
https://steamdb.info/depot/1262541/
https://steamdb.info/depot/1262601/
https://steamdb.info/depot/1313861/
https://steamdb.info/depot/1238811/

### Brief explanation of the change

Added Frostbite Engine.

### CODE REVIEW

**Comment by Lifeismana** [comment]
This is a duplicate, we already have Frostbite

**Comment by Suvitruf** [comment]
> 
> 
> This is a duplicate, we already have Frostbite

I don't see it in rules.ini o_O
Maybe the problen is with NVIDIA_Nsight_Aftermath?

**Comment by Lifeismana** [comment]
So NVIDIA_Nsight_Aftermath is a lib from Nvidia so it wouldn't work in a regex for an Engine.
rules.ini isn't the only way to detect, some engine can't be detected simply by a single file, we need to do a more complex detection, these get detected with the use of Evidence in rule.ini and the match gets done in test/FileDetector.php , Frostbite is one of those engine, you can see it in there

**Comment by Suvitruf** [comment]
> 
> 
> So NVIDIA_Nsight_Aftermath is a lib from Nvidia so it wouldn't work in a regex for an Engine.
> rules.ini isn't the only way to detect, some engine can't be detected simply by a single file, we need to do a more complex detection, these get detected with the use of Evidence in rule.ini and the match gets done in test/FileDetector.php , Frostbite is one of those engine, you can see it in there

Ok, thanks)

**Comment by xPaw** [comment]
If this `Engine.BuildInfo` rule works well without false positives, then the guessing in the php file for Frostbite could be removed.

Here's the matches:
```
    [engine.buildinfo.dll] => 10
    [engine.buildinfo_win64_retail.dll] => 8
    [engine.buildinfo_win32_retail.dll] => 2
    [engine.buildinfo_win32_retail_dll.dll] => 1
```

* [1222681 - Telstar - NFSH Content](https://steamdb.info/depot/1222681/)
* [1222691 - Telstar - DAI Content](https://steamdb.info/depot/1222691/)
* [1222731 - Maverick Content](https://steamdb.info/depot/1222731/)
* [1233571 - Telstar - MEC Content](https://steamdb.info/depot/1233571/)
* [1237951 - Telstar - SWB2 Content](https://steamdb.info/depot/1237951/)
* [1237981 - Telstar - SWB Content](https://steamdb.info/depot/1237981/)
* [1238001 - Mass Effect Andromeda - Content](https://steamdb.info/depot/1238001/)
* [1238811 - Battlefield V - Content](https://steamdb.info/depot/1238811/)
* [1238821 - Battlefield 3 - Content](https://steamdb.info/depot/1238821/)
* [1238841 - Telstar - BF1 Content](https://steamdb.info/depot/1238841/)
* [1238861 - Battlefield 4 - Content](https://steamdb.info/depot/1238861/)
* [1238881 - Battlefield Hardline - Content](https://steamdb.info/depot/1238881/)
* [1239521 - Madden NFL 21 Content](https://steamdb.info/depot/1239521/)
* [1262241 - PVZ Battle for Neighborville](https://steamdb.info/depot/1262241/)
* [1262541 - Need for Speed - Content](https://steamdb.info/depot/1262541/)
* [1262581 - Need for Speed Payback - Content](https://steamdb.info/depot/1262581/)
* [1262601 - Need For Speed Rivals - Content](https://steamdb.info/depot/1262601/)
* [1313861 - FIFA 21 - Content](https://steamdb.info/depot/1313861/)
* [1519351 - Madden NFL 22 Content](https://steamdb.info/depot/1519351/)

You can compare that to our current detection: https://steamdb.info/tech/Engine/Frostbite/ and see whether it misses or adds anything new.

**Comment by Suvitruf** [comment]
> If this `Engine.BuildInfo` rule works well without false positives, then the guessing in the php file for Frostbite could be removed.

I've checked it with the [games list](https://en.wikipedia.org/wiki/Frostbite_(game_engine)). Look like there there are no false positives.

**Comment by xPaw** [comment]
Then can you fix up the regex please, as well as match `engine.buildinfo_win32_retail_dll.dll` (notice the double dll, that's a real file).

And then remove this code: https://github.com/SteamDatabase/FileDetectionRuleSets/blob/main/tests/FileDetector.php#L222-L226

**Pull request closed without merging**
