### PR TITLE
Add CTG or Geo-Mod

### PR DESCRIPTION
**Pull request by diedyesterdaywastaken**
### SteamDB app page links to a few games using this

- [Agents of Mayhem](https://steamdb.info/app/304530/)
- [Descent: FreeSpace - The Great War](https://steamdb.info/app/273600/)
- [FreeSpace 2](https://steamdb.info/app/273620/)
- [Saints Row](https://steamdb.info/app/742420/)
- [Saints Row 2](https://steamdb.info/app/9480/)
- [Saints Row IV](https://steamdb.info/app/206420/)
- [Saints Row: Gat out of Hell](https://steamdb.info/app/301910/)
- [Saints Row: The Third](https://steamdb.info/app/55230/)
- [Saints Row: The Third Remastered](https://steamdb.info/app/978300/)
- [Summoner](https://steamdb.info/app/275570/)

### Brief explanation of the change

some more late night finds

### CODE REVIEW

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.Core\_Technology\_Group**

These apps now match: **(13)** [9480](https://steamdb.info/app/9480/depots/) [55230](https://steamdb.info/app/55230/depots/) [55370](https://steamdb.info/app/55370/depots/) [206420](https://steamdb.info/app/206420/depots/) [242590](https://steamdb.info/app/242590/depots/) [273600](https://steamdb.info/app/273600/depots/) [273620](https://steamdb.info/app/273620/depots/) [275570](https://steamdb.info/app/275570/depots/) [301910](https://steamdb.info/app/301910/depots/) [304530](https://steamdb.info/app/304530/depots/) [742420](https://steamdb.info/app/742420/depots/) [978300](https://steamdb.info/app/978300/depots/) [1154410](https://steamdb.info/app/1154410/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
needs non matching tests & some real strings
geo mod's link should be changed to https://redfactionwiki.com/wiki/Geo-Mod
i guess keeping the link to volution's farewell letter is fine

**Comment by SteamDB-Tracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.CTG\_OR\_Geo-Mod**

These apps now match: **(15)** [9480](https://steamdb.info/app/9480/depots/) [20500](https://steamdb.info/app/20500/depots/) [20530](https://steamdb.info/app/20530/depots/) [55110](https://steamdb.info/app/55110/depots/) [55230](https://steamdb.info/app/55230/depots/) [55370](https://steamdb.info/app/55370/depots/) [206420](https://steamdb.info/app/206420/depots/) [242590](https://steamdb.info/app/242590/depots/) [275570](https://steamdb.info/app/275570/depots/) [301910](https://steamdb.info/app/301910/depots/) [304530](https://steamdb.info/app/304530/depots/) [667720](https://steamdb.info/app/667720/depots/) [742420](https://steamdb.info/app/742420/depots/) [978300](https://steamdb.info/app/978300/depots/) [1154410](https://steamdb.info/app/1154410/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
the 2 appid missing 273600 273620

**Pull request merged**
