### PR TITLE
Update Winter mute

### LINKED ISSUE #412: Multiple Undetected Wintermute Games
### SteamDB link to the game

[Dark Fall: Lost Souls](https://steamdb.info/app/46750/)
[J.U.L.I.A.: Among the Stars](https://steamdb.info/app/257690)
[The Last Crown: Midnight Horror](https://steamdb.info/app/291770/)
[the white chamber](https://steamdb.info/app/299080/)

### What should it be detected as?

Engine.Wintermute

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/46750/
https://steamdb.info/app/257690/
https://steamdb.info/app/291770/

### Brief explanation of the change
Detect all DCP files as Wintermute engine.
Closes #412.

### CODE REVIEW

**Comment by MichaelHinrichs** [comment]
Dang it! Path "fdata.dcp" is listed in _NonMatchingTests.txt. Why? What non-wintermute games even have DCP files?

**Comment by MichaelHinrichs** [comment]
"J.U.L.I.A.: Among the Stars" has a "data_hd.dcp" and a "data_sd.dcp". If no one can find a false positive that would result from this change, i'm just going to delete "fdata.dcp" from "_NonMatchingTests.txt".

**Comment by Lifeismana** [comment]
Tom Clancy's Rainbow Six: Vegas & Tom Clancy's Rainbow Six: Vegas 2 aren't Winter mute games while they both have a dcp file

**Comment by MichaelHinrichs** [comment]
Dang it.

**Pull request closed without merging**
