### PR TITLE
add ShiVa3D

### LINKED ISSUE #586: Add ShiVa3D detection
### Some reference to the engine, such as the developer site or a wikipedia article.

https://web.archive.org/web/20180718043215/http://www.shiva-engine.com/
https://es.wikipedia.org/wiki/ShiVa

### SteamDB links

https://steamdb.info/app/346440/
https://steamdb.info/app/279520/

### Possible way to detect it

Contains files: S3DClient.cfg
*.stk

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

#586 

### Brief explanation of the change

closes #586

### CODE REVIEW

**Comment by Lifeismana** [comment]
Needs a non matching tesr

**Comment by diedyesterdaywashere** [comment]
image

i also messed up my main branch on accident 😄

**Comment by Lifeismana** [comment]
You can reset your main branch (make you're on your main branch) via `git reset --hard origin/main` (might not be origin/main , if the remote isn't named origin)

**Comment by diedyesterdaywashere** [comment]
almost that, yeah

image

**Pull request merged**
