### PR TITLE
Find steamsdk-godot.dll

### LINKED ISSUE #391: Multiple Godot games
### SteamDB link to the games

https://steamdb.info/app/2091300/
https://steamdb.info/app/2076850/
https://steamdb.info/app/2257790/
https://steamdb.info/app/2269170/

### What should it be detected as?

Engine.Godot

### Comment

They should be easy to detect, thanks to `steamsdk-godot.dll` and `libsteamsdk-godot.so` files.

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
https://steamdb.info/app/2264470/
https://steamdb.info/app/2091300/
https://steamdb.info/app/2076850/
https://steamdb.info/app/2257790/
https://steamdb.info/app/2269170/

### Brief explanation of the change
I found a Godot exclusive file. Also [overwatcheddude](https://github.com/overwatcheddude) found another. closes #391.

### CODE REVIEW

**Comment by overwatcheddude** [comment]
Can you include `libsteamsdk-godot.so` too? It is used by Linux clients. You can find some examples in #391

**Comment by MichaelHinrichs** [comment]
did it. Thank you for telling me about that.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

Would be interesting to also add heuristics for https://github.com/CoaguCo-Industries/GodotSteam which is another popular implementation of the Steamworks SDK for Godot, which can also leave traces in the files listing (e.g. `godotsteam.x86_64.dll` and `libgodotsteam.x86_64.so`, but I think there are more name possibilities).

That's probably best left for a separate PR though (CC @Gramps).

**Comment by xPaw** [comment]
godotsteam.dll is more popular variant of that.

**Comment by Gramps** [comment]
Yeah, we have about six variations on the said files.  I can either do a PR or just list them out.  Whatever is easier.

**Comment by xPaw** [comment]
Might as well make one regex to match these, and this library.

**Comment by Gramps** [comment]
There are files for Windows, OSX, and Linux and have the corresponding extensions of .dll, .so, and .dylib with OSX and Linux using libgodotsteam as the filename and Windows using godotsteam.  However, for GDExtension it gets a little more verbose, the previous rules apply but there are .debug variations and architecture variations like x86_32 and x86_64.  I think if it sees libgodotsteam or godotsteam, that's good enough, right?

**Comment by akien-mga** [comment]
If we don't mind a broad sweep, just looking for `*godotsteam*` might be enough?

**Comment by Lifeismana** [comment]
we do, so that won't we possible but `(?:^|/)(?:lib)?godotsteam` should work ?

**Comment by Gramps** [comment]
> If we don't mind a broad sweep, just looking for `*godotsteam*` might be enough?

It is the perfect commonality between all those files; K.I.S.S.  Cheers!

**Comment by xPaw** [comment]
I think literal regex of `godotsteam` should work, highly unlikely to match anything wrong.

**Pull request closed without merging**
