### PR TITLE
Update XAudio 2 SDK

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
### SteamDB app page links to a few games using this
[Asteroids](https://steamdb.info/app/2058260)

### Brief explanation of the change
Match any version.
Find XAudio2_[0-9]_64.dll.

### CODE REVIEW

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.XAudio2**

**10923** apps still match.

These apps no longer match: **(1)** [2650370](https://steamdb.info/app/2650370/depots/)

These apps now match: **(15)** [1306770](https://steamdb.info/app/1306770/depots/) [2006450](https://steamdb.info/app/2006450/depots/) [2058260](https://steamdb.info/app/2058260/depots/) [2116120](https://steamdb.info/app/2116120/depots/) [2238690](https://steamdb.info/app/2238690/depots/) [2423300](https://steamdb.info/app/2423300/depots/) [2555290](https://steamdb.info/app/2555290/depots/) [2761580](https://steamdb.info/app/2761580/depots/) [2803790](https://steamdb.info/app/2803790/depots/) [2839320](https://steamdb.info/app/2839320/depots/) [2854030](https://steamdb.info/app/2854030/depots/) [2884020](https://steamdb.info/app/2884020/depots/) [2888740](https://steamdb.info/app/2888740/depots/) [2904920](https://steamdb.info/app/2904920/depots/) [2906500](https://steamdb.info/app/2906500/depots/)

Please confirm that all these changed apps are correct.

**Comment by MichaelHinrichs** [comment]
The unmatch isn't my fault. All that's left of that app are the stock Visual C and DirectX depos.

**Comment by MichaelHinrichs** [comment]
[Asteroids](https://steamdb.info/app/2058260) is the only new match. All the rest were matched to XAudio 2 already. There are no false positives, so I see no reason to reject this PR.

**Comment by Lifeismana** [comment]
Doing this change for only one app is bot worth it

**Comment by MichaelHinrichs** [comment]
Well, it doesn't make it WORSE, now does it?

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.XAudio2**

**11063** apps still match.

These apps no longer match: **(3)** [1590010](https://steamdb.info/app/1590010/depots/) [2633070](https://steamdb.info/app/2633070/depots/) [2650370](https://steamdb.info/app/2650370/depots/)

These apps now match: **(33)** [908360](https://steamdb.info/app/908360/depots/) [1499130](https://steamdb.info/app/1499130/depots/) [1607140](https://steamdb.info/app/1607140/depots/) [1668580](https://steamdb.info/app/1668580/depots/) [1718540](https://steamdb.info/app/1718540/depots/) [1817800](https://steamdb.info/app/1817800/depots/) [1847120](https://steamdb.info/app/1847120/depots/) [1873140](https://steamdb.info/app/1873140/depots/) [1881440](https://steamdb.info/app/1881440/depots/) [2058260](https://steamdb.info/app/2058260/depots/) [2068540](https://steamdb.info/app/2068540/depots/) [2124300](https://steamdb.info/app/2124300/depots/) [2217180](https://steamdb.info/app/2217180/depots/) [2223620](https://steamdb.info/app/2223620/depots/) [2238690](https://steamdb.info/app/2238690/depots/) [2248330](https://steamdb.info/app/2248330/depots/) [2312980](https://steamdb.info/app/2312980/depots/) [2409000](https://steamdb.info/app/2409000/depots/) [2418480](https://steamdb.info/app/2418480/depots/) [2423300](https://steamdb.info/app/2423300/depots/) [2435470](https://steamdb.info/app/2435470/depots/) [2574470](https://steamdb.info/app/2574470/depots/) [2602300](https://steamdb.info/app/2602300/depots/) [2706230](https://steamdb.info/app/2706230/depots/) [2761580](https://steamdb.info/app/2761580/depots/) [2768010](https://steamdb.info/app/2768010/depots/) [2807290](https://steamdb.info/app/2807290/depots/) [2837640](https://steamdb.info/app/2837640/depots/) [2854030](https://steamdb.info/app/2854030/depots/) [2873050](https://steamdb.info/app/2873050/depots/) [2878180](https://steamdb.info/app/2878180/depots/) [2888160](https://steamdb.info/app/2888160/depots/) [2901040](https://steamdb.info/app/2901040/depots/)

Please confirm that all these changed apps are correct.

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.XAudio2**

**11395** apps still match.

These apps now match: **(7)** [2058260](https://steamdb.info/app/2058260/depots/) [2504480](https://steamdb.info/app/2504480/depots/) [2597880](https://steamdb.info/app/2597880/depots/) [2916710](https://steamdb.info/app/2916710/depots/) [2924850](https://steamdb.info/app/2924850/depots/) [2963110](https://steamdb.info/app/2963110/depots/) [2976390](https://steamdb.info/app/2976390/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
your modification doesn't detect anything 
\d should not be used, it matches other digit characters, [0-9] should be used instead
making regex modifications only for one app is not worth the decreased readability

**Pull request closed without merging**
