### PR TITLE
Add EA AntiCheat

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
### SteamDB app page links to a few games using this

https://steamdb.info/app/1811260

### Brief explanation of the change

Added rules for EA Anticheat

### CODE REVIEW

**Comment by Lifeismana** [comment]
Could you run `php tests/GenerateTestStrings.php` (see https://github.com/SteamDatabase/FileDetectionRuleSets/blob/main/CONTRIBUTING.md#tests) and add the changes that it does to this branch ?

**Comment by diedyesterdaywashere** [comment]
> Could you run `php tests/GenerateTestStrings.php` (see https://github.com/SteamDatabase/FileDetectionRuleSets/blob/main/CONTRIBUTING.md#tests) and add the changes that it does to this branch ?

i can't get php to run unfortunately

**Comment by diedyesterdaywashere** [comment]
> If you wish you can come to [steamdb's discord server](https://steamdb.info/discord/) and i could help you install/configure it but for now i'll run & add it myself

im already there :D diedyesterday#5745

**Comment by Lifeismana** [comment]
Looks good to me, thanks for the PR!

**Pull request merged**
