### PR TITLE
Update rules.ini to fully support Glacier

### PR DESCRIPTION
**Pull request by thecatontheceiling**
### Brief explanation of the change

Add full support for Glacier engine

### CODE REVIEW

**Comment by thecatontheceiling** [comment]
Not ready for merging because I haven't added tests yet

**Comment by thecatontheceiling** [comment]
Will open PR once I've added tests

**Comment by thecatontheceiling** [comment]
Okay it's ready for merge

**Comment by SteamTracker** [comment]
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.Glacier**

**7** apps still match.

These apps now match: **(15)** [6850](https://steamdb.info/app/6850/depots/) [6860](https://steamdb.info/app/6860/depots/) [6900](https://steamdb.info/app/6900/depots/) [6950](https://steamdb.info/app/6950/depots/) [8080](https://steamdb.info/app/8080/depots/) [28000](https://steamdb.info/app/28000/depots/) [28020](https://steamdb.info/app/28020/depots/) [32900](https://steamdb.info/app/32900/depots/) [35000](https://steamdb.info/app/35000/depots/) [35050](https://steamdb.info/app/35050/depots/) [203140](https://steamdb.info/app/203140/depots/) [205930](https://steamdb.info/app/205930/depots/) [247430](https://steamdb.info/app/247430/depots/) [1088850](https://steamdb.info/app/1088850/depots/) [1347780](https://steamdb.info/app/1347780/depots/)

Please confirm that all these changed apps are correct.

**Comment by Lifeismana** [comment]
32900 & 1088850 seems like false positives

**Comment by diedyesterdaywastaken** [comment]
> 32900 & 1088850 seems like false positives

1088850 uses their own [Dawn Engine](#772), idk about the other one

**Comment by thecatontheceiling** [comment]
Both are false positives. The resourcelib rule was just to detect Hitman: Absolution as it's the only Glacier game that uses that file extension. Will change that rule to detect something else.

**Comment by thecatontheceiling** [comment]
By the way, is there anyway I can run this bot manually? Would be very useful for checking false positives

**Comment by thecatontheceiling** [comment]
Nevermind, Guardians of the Galaxy is in fact NOT a false positive. That restaurant game is though

**Comment by thecatontheceiling** [comment]
Okay now it's ready for merge :DDDDD

**Comment by diedyesterdaywastaken** [comment]
> Guardians of the Galaxy is in fact NOT a false positive
https://www.eidosmontreal.com/news/powered-by-the-dawn-engine/ GotG runs on a heavily modded glacier 2 engine, called dawn engine, so we probably shouldn't count it as a glacier game

**Comment by diedyesterdaywastaken** [comment]
same way we don't detect apex legends as a source game even though it is *running* source, but modified

**Comment by diedyesterdaywastaken** [comment]
if there is no way around GotG then I think maintainers wouldn't really mind but it'd prob be best to avoid that

**Comment by thecatontheceiling** [comment]
Deus Ex Mankind Divided also uses the Dawn engine, ig I'll just change it back so that it only detects Absolution then

**Comment by thecatontheceiling** [comment]
Okay now it's ACTUALLY ready for merge (hopefully) :D

**Comment by thecatontheceiling** [comment]
cough

**Comment by thecatontheceiling** [comment]
Closed in favor of https://github.com/SteamDatabase/FileDetectionRuleSets/pull/848

**Pull request closed without merging**
